import { createFileRoute, Link } from "@tanstack/react-router";
import { allChangelogs, allReleaseAnnouncements } from "content-collections";
import { SiteFooter } from "~/components/landing-sections/site-footer";
import { SiteHeader } from "~/components/landing-sections/site-header";

export const Route = createFileRoute("/changelog")({
  head: () => ({
    meta: [
      { title: "Changelog - ax" },
      { name: "description", content: "Release announcements and generated changelog entries for ax." },
    ],
  }),
  loader: () => ({
    announcements: [...allReleaseAnnouncements].sort((a, b) => b.date.localeCompare(a.date)),
    changelog: allChangelogs[0] ?? null,
  }),
  component: ChangelogPage,
});

function ChangelogPage() {
  const { announcements, changelog } = Route.useLoaderData();
  const latest = announcements[0];

  return (
    <>
      <SiteHeader />
      <main className="release-page">
        <section className="release-hero">
          <p className="eyebrow">release notes</p>
          <h1>
            Changes with <em>context</em>.
          </h1>
          <p className="lede">
            Release Please keeps the generated changelog factual. The
            announcement layer explains what changed in product language.
          </p>
          <div className="release-actions">
            <a href="#announcements">Announcements</a>
            <a href="#generated">Generated changelog</a>
          </div>
        </section>

        <section id="announcements" className="release-section">
          <div className="section-kicker">announcement documents</div>
          {latest ? (
            <article className="release-feature">
              <div className="release-meta">
                <span>v{latest.version}</span>
                <span>{latest.date}</span>
              </div>
              <h2>{latest.title}</h2>
              <p>{latest.summary}</p>
              <Link to="/changelog" hash={`v${latest.version}`} className="release-anchor">
                Latest announcement
              </Link>
            </article>
          ) : (
            <p className="muted">No release announcements have been published yet.</p>
          )}

          <div className="release-list">
            {announcements.map((release) => (
              <article id={`v${release.version}`} key={release.version} className="release-entry">
                <div className="release-meta">
                  <span>v{release.version}</span>
                  <span>{release.date}</span>
                </div>
                <h3>{release.title}</h3>
                <p className="release-summary">{release.summary}</p>
                <div className="release-body">
                  <MarkdownLite content={release.content} />
                </div>
              </article>
            ))}
          </div>
        </section>

        <section id="generated" className="release-section">
          <div className="section-kicker">generated by release please</div>
          <article className="generated-changelog">
            {changelog ? (
              <MarkdownLite content={changelog.content} />
            ) : (
              <p className="muted">CHANGELOG.md has not been generated yet.</p>
            )}
          </article>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}

function MarkdownLite({ content }: { content: string }) {
  const blocks = content
    .replace(/^---[\s\S]*?---\s*/, "")
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean);

  return (
    <>
      {blocks.map((block, index) => {
        if (block.startsWith("# ")) {
          return <h2 key={index}>{renderInline(block.slice(2))}</h2>;
        }
        if (block.startsWith("## ")) {
          return <h3 key={index}>{renderInline(block.slice(3))}</h3>;
        }
        if (block.startsWith("### ")) {
          return <h4 key={index}>{renderInline(block.slice(4))}</h4>;
        }
        if (block.split("\n").every((line) => line.trim().startsWith("* "))) {
          return (
            <ul key={index}>
              {block.split("\n").map((line, itemIndex) => (
                <li key={itemIndex}>{renderInline(line.trim().slice(2))}</li>
              ))}
            </ul>
          );
        }
        return <p key={index}>{renderInline(block.replace(/\n/g, " "))}</p>;
      })}
    </>
  );
}

function renderInline(text: string) {
  const parts: Array<string | { text: string; href: string }> = [];
  const linkPattern = /\[([^\]]+)\]\(([^)]+)\)/g;
  let last = 0;
  let match: RegExpExecArray | null;

  while ((match = linkPattern.exec(text)) !== null) {
    if (match.index > last) parts.push(text.slice(last, match.index));
    parts.push({ text: match[1] ?? "", href: match[2] ?? "" });
    last = match.index + match[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));

  return parts.map((part, index) =>
    typeof part === "string"
      ? part
      : <a key={index} href={part.href}>{part.text}</a>
  );
}
