import { createFileRoute, notFound } from "@tanstack/react-router";
import { allChangelogs, allReleaseAnnouncements } from "content-collections";
import { SiteFooter } from "~/components/landing-sections/site-footer";
import { SiteHeader } from "~/components/landing-sections/site-header";
import { MarkdownLite } from "~/components/release-markdown";

export const Route = createFileRoute("/changelog_/$version")({
  head: ({ loaderData }) => ({
    meta: loaderData ? [
      { title: `${loaderData.release.title} - ax v${loaderData.release.version}` },
      { name: "description", content: loaderData.release.summary },
    ] : [
      { title: "Release not found - ax" },
    ],
  }),
  loader: ({ params }) => {
    const normalized = params.version.replace(/^v/, "");
    const release = allReleaseAnnouncements.find((item) => item.version === normalized);
    if (!release) throw notFound();
    const changelog = allChangelogs[0]?.content ?? "";
    return {
      release,
      generatedEntry: extractGeneratedEntry(changelog, normalized),
    };
  },
  component: ReleasePage,
});

function ReleasePage() {
  const { release, generatedEntry } = Route.useLoaderData();

  return (
    <>
      <SiteHeader />
      <main className="release-page release-detail-page">
        <section className="release-hero">
          <p className="eyebrow">release v{release.version}</p>
          <h1>{release.title}</h1>
          <p className="lede">{release.summary}</p>
          <div className="release-meta">
            <span>{release.date}</span>
            <span>ax v{release.version}</span>
          </div>
          <div className="release-actions">
            <a href="/changelog">All releases</a>
            <a href="#generated">Generated changelog</a>
          </div>
        </section>

        <section className="release-section">
          <div className="section-kicker">announcement</div>
          <article className="release-detail-body">
            <MarkdownLite content={release.content} />
          </article>
        </section>

        <section id="generated" className="release-section">
          <div className="section-kicker">generated by release please</div>
          <details className="generated-changelog">
            <summary>
              <span>Show generated changelog for v{release.version}</span>
              <small>commit-level detail from Release Please</small>
            </summary>
            <article>
              {generatedEntry ? (
                <MarkdownLite content={generatedEntry} />
              ) : (
                <p className="muted">No generated changelog entry found for this version.</p>
              )}
            </article>
          </details>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}

function extractGeneratedEntry(changelog: string, version: string): string | null {
  const escaped = version.replace(/\./g, "\\.");
  const heading = new RegExp(`^## \\[?${escaped}\\]?.*$`, "m");
  const match = changelog.match(heading);
  if (!match || match.index === undefined) return null;
  const rest = changelog.slice(match.index);
  const next = rest.slice(match[0].length).search(/^## /m);
  return next >= 0
    ? rest.slice(0, match[0].length + next).trim()
    : rest.trim();
}
