import { definePatternClassifier } from "../../../apps/axctl/src/classifiers/core.ts";

export const directionEventClassifier = definePatternClassifier({
    key: "direction-event",
    version: "0.1.0",
    description: "Identifies user instructions that should steer agent workflow or output choices.",
    skipControlText: true,
    patterns: [
        {
            test: /\buv\b|\b(use bun|use pnpm|don'?t use npm|don'?t use pip)\b/i,
            label: "direction",
            target: "tooling_preference",
            matched: "tooling_preference",
            polarity: "revise",
            durability: "repo_preference",
            confidence: 0.86,
            signals: ["direction:tooling_preference"],
        },
        {
            test: /\b(docker compose|docker-compose|compose up|dev database|dev db|predictable dev environment|use nix)\b/i,
            label: "direction",
            target: "dev_environment",
            matched: "dev_environment",
            polarity: "explore",
            durability: "repo_preference",
            confidence: 0.8,
            signals: ["direction:dev_environment"],
        },
        {
            test: /\b(ask fabijons|ask .*review|review this plan|roast it)\b/i,
            label: "direction",
            target: "review_request",
            matched: "review_request",
            polarity: "explore",
            durability: "one_off",
            confidence: 0.84,
            signals: ["direction:review_request"],
        },
        {
            test: /\b(don'?t want just html|not just html|want to see the results|show.*results)\b/i,
            label: "direction",
            target: "output_expectation",
            matched: "output_expectation",
            polarity: "revise",
            durability: "session_preference",
            confidence: 0.82,
            signals: ["direction:output_expectation"],
        },
    ],
});
