// packages/schema/src/duckdb-tables.ts
/** Manifest of every table in schema.duckdb.sql. Mirrors the SchemaTableSpec
 *  shape used by apps/axctl/src/queries/insights.ts (SCHEMA_TABLES) so the
 *  `ax insights schema` view can adopt it in wave 2. Exported, NOT wired. */
export interface DuckdbTableSpec {
    readonly table: string;
    readonly kind: "node" | "edge";
    readonly stage: "active" | "conditional" | "staged";
    readonly note: string;
}

export const DUCKDB_SCHEMA_TABLES: readonly DuckdbTableSpec[] = [
    { table: "skill", kind: "node", stage: "active", note: "Installed skills and slash commands." },
    { table: "skill_revision", kind: "node", stage: "active", note: "Append-only skill content-change log (drift over time)." },
    { table: "agent_def", kind: "node", stage: "active", note: "Agent definition files (~/.claude/agents) with reconcile lifecycle." },
    { table: "session", kind: "node", stage: "active", note: "Claude and Codex transcript sessions." },
    { table: "claude_sidecar_artifact", kind: "node", stage: "active", note: "Metadata-only Claude project sidecars linked to sessions when safe." },
    { table: "used_sidecar_artifact", kind: "edge", stage: "active", note: "Tool calls that produced, read, searched, or inspected Claude sidecar artifacts." },
    { table: "agent_provider", kind: "node", stage: "active", note: "Agent transcript provider identities." },
    { table: "agent_model", kind: "node", stage: "active", note: "Agent model catalogue with pricing and context metadata." },
    { table: "agent_session", kind: "node", stage: "active", note: "Provider-native session rows linked to normalized sessions." },
    { table: "agent_event", kind: "node", stage: "active", note: "Provider-native event stream rows." },
    { table: "turn", kind: "node", stage: "active", note: "Transcript turns and tool result turns." },
    { table: "file", kind: "node", stage: "active", note: "Canonical repository-relative files plus legacy file rows." },
    { table: "symbol", kind: "node", stage: "staged", note: "Reserved symbol mention catalogue for code-context queries." },
    { table: "error_signature", kind: "node", stage: "staged", note: "Reserved normalized error signatures for recurrence queries." },
    { table: "commit", kind: "node", stage: "active", note: "Git commits imported from tracked repositories." },
    { table: "repository", kind: "node", stage: "active", note: "Stable repository identities, preferring normalized remotes." },
    { table: "checkout", kind: "node", stage: "active", note: "Local checkout/worktree paths for repositories." },
    { table: "workspace", kind: "node", stage: "staged", note: "Reserved for cross-checkout workspace grouping." },
    { table: "tool", kind: "node", stage: "active", note: "Normalized CLI, MCP, and agent tool identities." },
    { table: "tool_call", kind: "node", stage: "active", note: "Claude and Codex tool calls with errors and command fields." },
    { table: "content_type", kind: "node", stage: "active", note: "Closed content-type taxonomy for tool outputs." },
    { table: "has_content", kind: "edge", stage: "active", note: "tool_call -> content_type edge; denormalizes session + bytes." },
    { table: "plan", kind: "node", stage: "active", note: "Current plan state per session/source." },
    { table: "plan_item", kind: "node", stage: "active", note: "Latest stable plan items for each plan." },
    { table: "artifact", kind: "node", stage: "active", note: "Generated reports, dogfood artifacts, and guidance evidence." },
    { table: "content_document", kind: "node", stage: "active", note: "Parsed document containers for markdown artifacts and plans." },
    { table: "content_block", kind: "node", stage: "active", note: "Searchable markdown block chunks with source offsets." },
    { table: "content_atom", kind: "node", stage: "active", note: "Fine-grained parsed document facts and evidence atoms." },
    { table: "mentions_file", kind: "edge", stage: "active", note: "Content atom to file mention edges." },
    { table: "mentions_commit", kind: "edge", stage: "active", note: "Content atom to commit mention edges." },
    { table: "mentions_artifact", kind: "edge", stage: "active", note: "Content atom to artifact mention edges." },
    { table: "plan_snapshot", kind: "node", stage: "active", note: "Point-in-time TodoWrite/update_plan snapshots." },
    { table: "compaction", kind: "node", stage: "active", note: "Context-compaction events per harness (summarize/history-replacement/encrypted)." },
    { table: "insight", kind: "node", stage: "active", note: "Imported Claude usage-data insight facets." },
    { table: "friction_event", kind: "node", stage: "active", note: "Tool failures, imported insight friction, and derived friction." },
    { table: "turn_analysis", kind: "node", stage: "active", note: "Per-turn message analysis for sparse user feedback and assistant behavior." },
    { table: "reaction_event", kind: "node", stage: "active", note: "Context-aware user reaction events built from prior assistant/tool context." },
    { table: "classifier_definition", kind: "node", stage: "active", note: "Installed classifier definitions and declared label/target contracts." },
    { table: "classifier_run", kind: "node", stage: "active", note: "Classifier execution runs over transcript event windows." },
    { table: "classifier_result", kind: "node", stage: "active", note: "Versioned classifier labels attached to turns and other subjects." },
    { table: "classifier_graph_node", kind: "node", stage: "active", note: "Generic classifier graph nodes projected from package operations." },
    { table: "classifier_graph_edge", kind: "node", stage: "active", note: "Generic classifier graph edges projected from package operations." },
    { table: "classifier_graph_fact", kind: "node", stage: "active", note: "Generic classifier graph facts projected from package operations." },
    { table: "transcript_label_review", kind: "node", stage: "active", note: "Human/agent review verdicts for mined transcript label candidates." },
    { table: "transcript_label_vector", kind: "node", stage: "active", note: "Embedding vectors and nearest-neighbor refs for transcript label candidates." },
    { table: "semantic_signal", kind: "node", stage: "active", note: "Reusable meanings promoted from analyzed turns." },
    { table: "diagnostic_event", kind: "node", stage: "active", note: "Derived diagnostics from failed commands and friction." },
    { table: "guidance", kind: "node", stage: "staged", note: "Persisted behavior controls such as rules, skills, hooks, and commands." },
    { table: "guidance_version", kind: "node", stage: "staged", note: "Legacy guidance history table kept until migration to guidance_revision." },
    { table: "guidance_source", kind: "node", stage: "active", note: "Observed repo-local and global storage authorities for Guidance." },
    { table: "guidance_revision", kind: "node", stage: "active", note: "Content-hashed observed Guidance revisions with evidence strength." },
    { table: "guidance_config_artifact", kind: "node", stage: "active", note: "Metadata-only inventory of provider guidance/config artifacts." },
    { table: "stack", kind: "node", stage: "active", note: "Lean technology/platform records for applicability matching." },
    { table: "command_outcome", kind: "node", stage: "active", note: "Semantic command result classifications." },
    { table: "user_message_ngram", kind: "node", stage: "active", note: "Derived user-language n-grams for preference and correction mining." },
    { table: "workflow_epoch", kind: "node", stage: "active", note: "Derived workflow eras for before/after comparisons." },
    { table: "session_token_usage", kind: "node", stage: "active", note: "Actual or estimated session token/cache usage." },
    { table: "turn_token_usage", kind: "node", stage: "active", note: "Provider-derived per-turn token/cache usage and priced cost estimates." },
    { table: "session_health", kind: "node", stage: "active", note: "Derived session-level workflow, context, and interruption health." },
    { table: "session_metrics", kind: "node", stage: "active", note: "Graph-derived per-session metrics (durability, time-to-land, loc)." },
    { table: "fragility_cascade", kind: "node", stage: "active", note: "Precomputed cross-session fragility-cascade signal edges (origin session -> downstream fixer)." },
    { table: "commit_classification", kind: "node", stage: "active", note: "Commit message lifecycle classification." },
    { table: "branch", kind: "node", stage: "staged", note: "GitHub branch state for delivery analytics." },
    { table: "pull_request", kind: "node", stage: "staged", note: "GitHub pull request state for delivery analytics." },
    { table: "review_event", kind: "node", stage: "staged", note: "GitHub review events for delivery analytics." },
    { table: "check_run", kind: "node", stage: "staged", note: "GitHub check runs for delivery analytics." },
    { table: "delivery_outcome", kind: "node", stage: "staged", note: "Session delivery/promotion outcome summaries." },
    { table: "workflow_snapshot", kind: "node", stage: "active", note: "Precomputed dashboard workflow payload used by /api/workflow." },
    { table: "phase_span", kind: "node", stage: "staged", note: "Session workflow phase spans and phase-level counters." },
    { table: "skill_candidate", kind: "node", stage: "active", note: "Evidence-backed candidate skills or guardrails." },
    { table: "ingest_run", kind: "node", stage: "active", note: "Top-level ingest execution telemetry." },
    { table: "ingest_stage", kind: "node", stage: "active", note: "Per-stage ingest execution telemetry." },
    { table: "ingest_event", kind: "node", stage: "active", note: "Append-like ingest progress events." },
    { table: "query_sample", kind: "node", stage: "staged", note: "Reserved query execution samples." },
    { table: "graph_health_check", kind: "node", stage: "staged", note: "Persisted graph health check rows." },
    { table: "role", kind: "node", stage: "active", note: "Skill role labels used for weighting and grouping." },
    { table: "plays_role", kind: "edge", stage: "active", note: "Skill-to-role classification edges." },
    { table: "invoked", kind: "edge", stage: "active", note: "Turn-to-skill invocation edges." },
    { table: "loaded", kind: "edge", stage: "active", note: "Session-to-skill auto-load activations (subagent skills: frontmatter); separate from invoked." },
    { table: "proposed", kind: "edge", stage: "active", note: "Skills mentioned but not invoked." },
    { table: "edited", kind: "edge", stage: "active", note: "Turn-to-file edit edges." },
    { table: "mentioned_file", kind: "edge", stage: "staged", note: "Reserved turn-to-file mention edges." },
    { table: "mentioned_symbol", kind: "edge", stage: "staged", note: "Reserved turn-to-symbol mention edges." },
    { table: "mentioned_error", kind: "edge", stage: "staged", note: "Reserved turn-to-error mention edges." },
    { table: "read_file", kind: "edge", stage: "staged", note: "Reserved tool-call-to-file read evidence edges." },
    { table: "searched_file", kind: "edge", stage: "staged", note: "Reserved tool-call-to-file search evidence edges." },
    { table: "corrected_by", kind: "edge", stage: "active", note: "Assistant turns followed by user correction signals." },
    { table: "expresses", kind: "edge", stage: "active", note: "Turn-to-semantic-signal evidence edges." },
    { table: "reacts_to", kind: "edge", stage: "active", note: "User reaction turns linked to the prior assistant turn they approve, reject, or revise." },
    { table: "has_classification", kind: "edge", stage: "active", note: "Turn-to-classifier-result edges for versioned labels." },
    { table: "produced", kind: "edge", stage: "active", note: "Session-to-commit edges." },
    { table: "touched", kind: "edge", stage: "active", note: "Commit-to-file edges with additions/deletions/status." },
    { table: "later_fixed_by", kind: "edge", stage: "active", note: "Feature commit to later overlapping fix commit relation." },
    { table: "suggests_skill", kind: "edge", stage: "active", note: "Fix or evidence commit to skill candidate relation." },
    { table: "has_checkout", kind: "edge", stage: "active", note: "Repository-to-checkout edges." },
    { table: "concerns", kind: "edge", stage: "active", note: "Generic evidence edges, currently used for tool/skill and insight/session links." },
    { table: "resulted_in", kind: "edge", stage: "staged", note: "Reserved generic outcome relation." },
    { table: "produced_artifact", kind: "edge", stage: "staged", note: "Reserved producer-to-artifact relation." },
    { table: "has_artifact", kind: "edge", stage: "staged", note: "Reserved owner-to-artifact relation." },
    { table: "derived_from", kind: "edge", stage: "active", note: "Provenance relation for derived guidance and artifacts." },
    { table: "skill_paired", kind: "edge", stage: "active", note: "Derived skill co-occurrence edges." },
    { table: "recovered_by", kind: "edge", stage: "active", note: "Derived recovery edges after an error turn." },
    { table: "spawned", kind: "edge", stage: "active", note: "Parent-to-child delegated session edges." },
    { table: "advice", kind: "node", stage: "active", note: "Hook advice ledger rows from ~/.ax/hooks/advise-log.jsonl (route-dispatch additionalContext)." },
    { table: "agent_event_child", kind: "edge", stage: "active", note: "Provider-event parent-child edges." },
    { table: "used_model", kind: "edge", stage: "active", note: "Session-to-agent-model usage edges." },
    { table: "agent_used_model", kind: "edge", stage: "active", note: "Provider-session-to-agent-model usage edges." },
    { table: "skill_triage_decision", kind: "node", stage: "active", note: "Dashboard keep/archive/review decisions per skill." },
    { table: "harness_hook_event", kind: "node", stage: "active", note: "Native agent harness hook lifecycle events." },
    { table: "hook_command_invocation", kind: "node", stage: "active", note: "Commands invoked by native harness hooks." },
    { table: "ax_invocation", kind: "node", stage: "active", note: "ax's own CLI invocations (redacted) for self-telemetry / utilization." },
    { table: "feedback_case_type", kind: "node", stage: "active", note: "Feedback backtest case definitions." },
    { table: "feedback_case_result", kind: "node", stage: "active", note: "Feedback backtest results." },
    { table: "hook_fire", kind: "node", stage: "active", note: "Runtime file-context hook decisions." },
    { table: "proposal", kind: "node", stage: "active", note: "Polymorphic shortlist of repeated workflow improvement candidates." },
    { table: "directive_ngram", kind: "node", stage: "active", note: "Per-user n-gram lift table: which user-turn markers predict captured outcomes (directive mining v2, #587)." },
    { table: "skill_proposal", kind: "node", stage: "active", note: "Typed payload rows for skill-form proposals." },
    { table: "subagent_proposal", kind: "node", stage: "active", note: "Typed payload rows for subagent-form proposals." },
    { table: "hook_proposal", kind: "node", stage: "active", note: "Typed payload rows for hook-form proposals." },
    { table: "guidance_proposal", kind: "node", stage: "active", note: "Typed payload rows for guidance-file proposals." },
    { table: "automation_proposal", kind: "node", stage: "active", note: "Typed payload rows for automation-form proposals." },
    { table: "cites_evidence", kind: "edge", stage: "active", note: "Proposal-to-evidence edges." },
    { table: "experiment", kind: "node", stage: "active", note: "Accepted proposals and scaffold/verdict state." },
    { table: "opportunity", kind: "edge", stage: "active", note: "Experiment trigger recurrence evidence edges." },
    { table: "checkpoint", kind: "node", stage: "active", note: "Experiment measurement snapshots and user verdicts." },
    { table: "dogfood_run", kind: "node", stage: "active", note: "Terminal dogfood scenario results." },
    { table: "retro", kind: "node", stage: "active", note: "Structured session retrospectives." },
    { table: "reviewed", kind: "edge", stage: "active", note: "Session-to-retro review edges." },
    { table: "ingest_file_state", kind: "node", stage: "active", note: "Per-source ingest watermark (mtime/size/sha) for skip-unchanged re-ingest." },
    { table: "otel_metric_point", kind: "node", stage: "active", note: "Harness OTLP metric data points (cost/token/usage)." },
    { table: "otel_span", kind: "node", stage: "active", note: "Harness OTLP trace spans (Codex session_loop + children)." },
    { table: "otel_log_event", kind: "node", stage: "active", note: "Harness OTLP log events (codex events incl. token usage)." },
    { table: "harness_tool_event", kind: "node", stage: "active", note: "Shared tool decision/result projection from transcript, hooks, and OTLP events." },
    { table: "harness_run_context", kind: "node", stage: "active", note: "Shared run context projection from transcript and OTLP startup events." },
    { table: "wrapped_card", kind: "node", stage: "active", note: "Agent-authored Wrapped recap cards (ax wrapped publish)." },
    { table: "telemetry_of", kind: "edge", stage: "active", note: "Edge: session -> otel telemetry row (drawn at ingest)." },
    { table: "run_evidence_event", kind: "node", stage: "active", note: "Run evidence ledger (#578): normalized claim/observation/verification/boundary events over the graph; backing distinguishes model claim vs tool-backed." },
    { table: "run_evidence_ref", kind: "node", stage: "active", note: "Run evidence ledger (#578): structural refs/hashes off an evidence event; privacy_level keeps payloads out by default." },
];
