import { definePatternClassifier } from "../core.ts";

export const correctionEventClassifier = definePatternClassifier({
    key: "correction-event",
    version: "0.1.0",
    description: "Identifies user corrections and what was wrong with the agent response or interpretation.",
    skipControlText: true,
    patterns: [
        {
            test: /\b(don'?t want just html|not just html|want to see the results|actually useful things|apply to surrealml)\b/i,
            label: "correction",
            target: "wrong_artifact",
            matched: "wrong_artifact",
            polarity: "revise",
            durability: "session_preference",
            confidence: 0.86,
            signals: ["correction:wrong_artifact"],
        },
        {
            test: /\b(previous context|not only the user message|what agent was done|caused this message|missed the context)\b/i,
            label: "correction",
            target: "missing_context",
            matched: "missing_context",
            polarity: "revise",
            durability: "repo_preference",
            confidence: 0.88,
            signals: ["correction:missing_context"],
        },
        {
            test: /\b(direction thing|not a correction|misclassified|classification.*wrong|wrong classifier)\b/i,
            label: "correction",
            target: "misclassified_intent",
            matched: "misclassified_intent",
            polarity: "revise",
            durability: "repo_preference",
            confidence: 0.82,
            signals: ["correction:misclassified_intent"],
        },
        {
            test: /\b(accepted workflow candidate|persisted review fact)\b.*\b(correction_or_rejection_signal|workflow-state correction|workflow_state|add_context_guardrail)\b/i,
            label: "correction",
            target: "workflow_state",
            matched: "workflow_state_reviewed_candidate",
            polarity: "revise",
            durability: "repo_preference",
            confidence: 0.84,
            signals: ["correction:workflow_state", "source:reviewed_workflow_candidate"],
        },
        {
            test: /^(no|nope|nah)\b|\b(wrong|not what i asked|not that)\b/i,
            label: "correction",
            target: "wrong_output",
            matched: "wrong_output",
            polarity: "revise",
            durability: "session_preference",
            confidence: 0.74,
            signals: ["correction:wrong_output"],
        },
    ],
});
