import { describe, expect, test } from "bun:test";
import { fileRecordKey, toolCallRecordKey, turnRecordKey } from "./record-keys.ts";
import {
    __testExtractClaudeJsonlLines,
    claudeConcurrency,
    transcriptEditFileRecordKey,
} from "./transcripts.ts";

describe("Claude transcript extraction", () => {
    test("claudeConcurrency rejects invalid values", () => {
        expect(claudeConcurrency(undefined)).toBe(4);
        expect(claudeConcurrency("8")).toBe(8);
        expect(claudeConcurrency("0")).toBe(4);
        expect(claudeConcurrency("nope")).toBe(4);
    });

    test("extracts plain user prompts and classifies context versus tool-result turns", () => {
        const longTaskText = `Find the files that define transcript ingest.\n${"x".repeat(620)}`;
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:00.000Z",
                    message: {
                        role: "user",
                        content: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:01.000Z",
                    message: {
                        role: "user",
                        content: longTaskText,
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:02.000Z",
                    message: {
                        role: "user",
                        content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:03.000Z",
                    message: {
                        role: "user",
                        content: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:04.000Z",
                    message: {
                        role: "user",
                        content: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:05.000Z",
                    message: {
                        role: "user",
                        content: [
                            {
                                type: "tool_result",
                                tool_use_id: "toolu_read",
                                content: "src/ingest/transcripts.ts",
                            },
                        ],
                    },
                }),
            ],
            "-tmp-project",
            "claude-user-text",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(
            extracted.turns.map((turn) => ({
                role: turn.role,
                text: turn.text,
                text_excerpt: turn.text_excerpt,
                message_kind: turn.message_kind,
                intent_kind: turn.intent_kind,
            })),
        ).toEqual([
            {
                role: "user",
                text: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                text_excerpt: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                message_kind: "context",
                intent_kind: "system_context",
            },
            {
                role: "user",
                text: longTaskText,
                text_excerpt: longTaskText.slice(0, 500),
                message_kind: "task",
                intent_kind: "organic_task",
            },
            {
                role: "user",
                text: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                text_excerpt: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                message_kind: "context",
                intent_kind: "system_context",
            },
            {
                role: "user",
                text: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                text_excerpt: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                message_kind: "context",
                intent_kind: "skill_context",
            },
            {
                role: "user",
                text: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                text_excerpt: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                message_kind: "control",
                intent_kind: "control",
            },
            {
                role: "user",
                text: null,
                text_excerpt: null,
                message_kind: "tool_result",
                intent_kind: "tool_result",
            },
        ]);
    });

    test("extracts tool calls, tool results, skill relations, edits, and TodoWrite snapshots", () => {
        const longOutput = `${"x".repeat(1600)}\nfinal line`;
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/agentctl",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_skill",
                                name: "Skill",
                                input: {
                                    skill: "superpowers:test-driven-development",
                                    reason: "Need TDD",
                                },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_bash",
                                name: "Bash",
                                input: {
                                    command: "cd src && bun test src/ingest/transcripts.test.ts",
                                },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_edit",
                                name: "Edit",
                                input: {
                                    file_path: "src/ingest/transcripts.ts",
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T10:00:01.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_result",
                                tool_use_id: "toolu_bash",
                                is_error: true,
                                content: longOutput,
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:02.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_1",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect schema",
                                            activeForm: "Inspecting schema",
                                            status: "completed",
                                        },
                                        {
                                            content: "Wire writers",
                                            activeForm: "Wiring writers",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:03.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_2",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect schema",
                                            activeForm: "Inspecting schema",
                                            status: "completed",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-agentctl",
            "session-abc",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.toolCalls).toHaveLength(5);
        expect(extracted.edits).toEqual([
            {
                session: "session-abc",
                seq: 1,
                ts: "2026-05-09T10:00:00.000Z",
                repo: "agentctl",
                path: "/Users/necmttn/Projects/agentctl/src/ingest/transcripts.ts",
                tool: "Edit",
            },
        ]);

        const skillCall = extracted.toolCalls.find((call) => call.toolName === "Skill");
        expect(skillCall).toMatchObject({
            provider: "claude",
            toolKind: "skill",
            sessionId: "session-abc",
            seq: 1,
            turnKey: turnRecordKey("session-abc", 1),
            callId: "toolu_skill",
            cwd: "/Users/necmttn/Projects/agentctl",
            hasError: false,
        });
        expect(skillCall?.inputJson).toEqual({
            skill: "superpowers:test-driven-development",
            reason: "Need TDD",
        });
        expect(skillCall?.rawJson).toMatchObject({
            type: "tool_use",
            id: "toolu_skill",
            name: "Skill",
        });

        const bashCall = extracted.toolCalls.find((call) => call.toolName === "Bash");
        expect(bashCall).toMatchObject({
            provider: "claude",
            toolKind: "builtin",
            sessionId: "session-abc",
            seq: 1,
            turnKey: turnRecordKey("session-abc", 1),
            callId: "toolu_bash",
            commandText: "cd src && bun test src/ingest/transcripts.test.ts",
            commandToolName: "bun",
            commandNorm: "bun test",
            hasError: true,
        });
        expect(typeof bashCall?.errorText).toBe("string");
        expect(bashCall?.outputJson).toBe(longOutput);
        expect(bashCall?.outputExcerpt?.length).toBeLessThanOrEqual(1200);
        expect(bashCall?.outputExcerpt).toBe(bashCall?.errorText);

        expect(extracted.skillRelations).toEqual([
            {
                toolCallKey: toolCallRecordKey({
                    sessionId: "session-abc",
                    seq: 1,
                    callId: "toolu_skill",
                }),
                skillName: "superpowers:test-driven-development",
                ts: "2026-05-09T10:00:00.000Z",
                reason: "Claude Skill tool invocation",
                labels: { provider: "claude", toolName: "Skill", source: "transcript" },
                metrics: { turnSeq: 1 },
            },
        ]);

        expect(extracted.planSnapshots).toHaveLength(2);
        const [firstSnapshot, secondSnapshot] = extracted.planSnapshots;
        expect(firstSnapshot).toMatchObject({
            sessionId: "session-abc",
            source: "claude_todowrite",
            status: "in_progress",
            createdAt: "2026-05-09T10:00:02.000Z",
            updatedAt: "2026-05-09T10:00:02.000Z",
            ts: "2026-05-09T10:00:02.000Z",
            toolCallKey: toolCallRecordKey({
                sessionId: "session-abc",
                seq: 3,
                callId: "toolu_todo_1",
            }),
        });
        expect(firstSnapshot.items).toEqual([
            expect.objectContaining({
                seq: 1,
                content: "Inspect schema",
                activeForm: "Inspecting schema",
                status: "completed",
            }),
            expect.objectContaining({
                seq: 2,
                content: "Wire writers",
                activeForm: "Wiring writers",
                status: "in_progress",
            }),
        ]);
        expect(secondSnapshot.planKey).toBe(firstSnapshot.planKey);
        expect(secondSnapshot.createdAt).toBe("2026-05-09T10:00:02.000Z");
        expect(secondSnapshot.updatedAt).toBe("2026-05-09T10:00:03.000Z");
        expect(secondSnapshot.snapshotKey).not.toBe(firstSnapshot.snapshotKey);
    });

    test("assigns stable fallback ids to anonymous tool uses in the same turn", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T11:00:00.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                name: "Bash",
                                input: { command: "pwd" },
                            },
                            {
                                type: "tool_use",
                                name: "Bash",
                                input: { command: "git status --short" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-agentctl",
            "session-anonymous",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.toolCalls.map((call) => call.callId)).toEqual([
            "anonymous_tool_use_000001_001",
            "anonymous_tool_use_000001_002",
        ]);
        expect(
            new Set(
                extracted.toolCalls.map((call) =>
                    toolCallRecordKey({
                        sessionId: call.sessionId,
                        seq: call.seq,
                        callId: call.callId ?? null,
                    }),
                ),
            ).size,
        ).toBe(2);
    });

    test("turn IDs use centralized turnRecordKey format", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/agentctl",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_bash",
                                name: "Bash",
                                input: { command: "pwd" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-agentctl",
            "session-id-check",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        const expectedTurnKey = turnRecordKey("session-id-check", 1);
        const bashCall = extracted.toolCalls.find((c) => c.toolName === "Bash");
        expect(bashCall?.turnKey).toBe(expectedTurnKey);
    });

    test("edited-file IDs use local path identity before repository canonicalization", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/agentctl",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_check",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/Projects/agentctl/src/a.ts" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-agentctl",
            "session-file-check",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        const expectedFileKey = fileRecordKey("_", "/Users/necmttn/Projects/agentctl/src/a.ts");
        expect(extracted.edits).toHaveLength(1);
        const edit = extracted.edits[0];
        expect(transcriptEditFileRecordKey(edit?.path ?? "")).toBe(expectedFileKey);
    });

    test("edited-file IDs merge the same local file across cwd-derived repo labels", () => {
        const first = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/apps",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_apps",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/.claude/hooks/block-em-dash.sh" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-apps",
            "session-file-apps",
        );
        const second = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/quera",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_quera",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/.claude/hooks/block-em-dash.sh" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-quera",
            "session-file-quera",
        );

        expect(first?.edits[0]?.repo).toBe("apps");
        expect(second?.edits[0]?.repo).toBe("quera");
        expect(transcriptEditFileRecordKey(first?.edits[0]?.path ?? ""))
            .toBe(transcriptEditFileRecordKey(second?.edits[0]?.path ?? ""));
    });

    test("keeps TodoWrite plan item keys stable when the same sequence changes", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T12:00:00.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_1",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect failing ingest",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T12:00:01.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_2",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Fix plan item identity",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-agentctl",
            "claude-plan-session",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.planSnapshots).toHaveLength(2);
        expect(extracted.planSnapshots[0]?.items[0]?.key).toBe(
            extracted.planSnapshots[1]?.items[0]?.key,
        );
    });
});
