#!/usr/bin/env bun
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const SRC_DIR = resolve(REPO_ROOT, "src/ingest");
const OUT_PATH = resolve(REPO_ROOT, "docs/how-ax-sees-your-work.generated.mdx");

interface Stage {
    readonly name: string;
    readonly rationale: string;
    readonly inputs?: string;
    readonly outputs?: string;
    readonly order: number;
    readonly file: string;
}

// Matches @tag value-text where value-text continues until the next @tag
// or the end of the JSDoc block. Continuation lines start with `  * `.
const tagPattern =
    /@(stage|rationale|inputs|outputs|order)\s+([^\n]+(?:\n\s*\*\s+[^\n@*][^\n]*)*)/g;

const parseFile = async (path: string): Promise<Stage | null> => {
    const text = await readFile(path, "utf8");
    const headerMatch = text.match(/^\s*\/\*\*([\s\S]*?)\*\//);
    if (!headerMatch) return null;
    const header = headerMatch[1] ?? "";
    const tags: Record<string, string> = {};
    for (const m of header.matchAll(tagPattern)) {
        const key = m[1] as string;
        const raw = (m[2] ?? "").replace(/\n\s*\*\s+/g, " ").trim();
        tags[key] = raw;
    }
    if (!tags.stage || !tags.rationale) return null;

    let order = 999;
    if (tags.order !== undefined) {
        const parsed = Number.parseInt(tags.order, 10);
        if (Number.isNaN(parsed)) {
            console.warn(`[extract-stage-rationale] warning: @order "${tags.order}" in ${basename(path)} is not a number - defaulting to 999`);
        } else {
            order = parsed;
        }
    }

    return {
        name: tags.stage,
        rationale: tags.rationale,
        inputs: tags.inputs,
        outputs: tags.outputs,
        order,
        file: `src/ingest/${basename(path)}`,
    };
};

const main = async () => {
    const files = (await readdir(SRC_DIR))
        .filter((name) => name.endsWith(".ts") && !name.endsWith(".test.ts"))
        .sort();

    const stages: Stage[] = [];
    for (const name of files) {
        const stage = await parseFile(join(SRC_DIR, name));
        if (stage) stages.push(stage);
    }

    if (stages.length === 0) {
        console.error("[extract-stage-rationale] error: no stages found in src/ingest/");
        console.error("  Add @stage and @rationale tags to a leading /** */ JSDoc block in at least one src/ingest/*.ts file.");
        process.exit(2);
    }

    stages.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

    const sections = stages.map((s) => {
        const lines: string[] = [
            `### ${s.name}`,
            ``,
            s.rationale,
            ``,
        ];
        if (s.inputs) lines.push(`**Inputs:** ${s.inputs}`, ``);
        if (s.outputs) lines.push(`**Outputs:** ${s.outputs}`, ``);
        lines.push(`_Source: \`${s.file}\`_`, ``);
        return lines.join("\n");
    });

    const out = [
        `{/* GENERATED by scripts/extract-stage-rationale.ts - do not edit by hand. */}`,
        `{/* Edit @rationale comments on src/ingest/*.ts instead. */}`,
        ``,
        ...sections,
    ].join("\n");

    await mkdir(dirname(OUT_PATH), { recursive: true });
    await writeFile(OUT_PATH, out, "utf8");
    console.log(`wrote ${stages.length} stage(s) to ${OUT_PATH}`);
};

await main();
