#!/usr/bin/env bun
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const SRC_DIR = resolve(REPO_ROOT, "apps/axctl/src/ingest");
const OUT_PATH = resolve(REPO_ROOT, "docs/how-ax-sees-your-work.generated.mdx");

/**
 * Annotation contract for src/ingest/*.ts files:
 *
 *   /**
 *    * @stage     <display name>           (required)
 *    * @rationale <prose, 1-3 sentences,
 *    *            product-level voice>     (required)
 *    *
 *    *            Multi-line continuation: each follow-up line must be
 *    *            ` *   text` (space, star, space-or-tab+). Do NOT put a
 *    *            blank ` *` line between tags - the continuation regex
 *    *            requires non-blank continuation text.
 *    *
 *    * @inputs    <short description>       (optional)
 *    * @outputs   <short description>       (optional)
 *    * @order     <integer, lower = earlier> (optional, default 999)
 *    *\/
 *
 * The block must be the FIRST /** encountered in the file. Leading
 * `//` line comments or shebangs are tolerated. Files without a
 * @stage or @rationale tag are silently skipped (used to filter
 * non-stage helper files).
 *
 * Generated output: docs/how-ax-sees-your-work.generated.mdx
 */
interface Stage {
    readonly name: string;
    readonly rationale: string;
    readonly inputs?: string;
    readonly outputs?: string;
    readonly order: number;
    readonly file: string;
}

// Matches @tag value-text where value-text continues until the next @tag
// or the end of the JSDoc block. Continuation lines start with `  * `.
// `[ \t]+` (not `\s+`) so a blank ` *` line cannot bridge to the next tag.
const tagPattern =
    /@(stage|rationale|inputs|outputs|order)[ \t]+([^\n]+(?:\n[ \t]*\*[ \t]+[^\n@*][^\n]*)*)/g;

const parseFile = async (path: string): Promise<Stage | null> => {
    const text = await readFile(path, "utf8");
    // Match the FIRST `/** ... */` block anywhere in the file (no leading
    // anchor) so leading `//` comments or shebangs do not silently skip it.
    const headerMatch = text.match(/\/\*\*([\s\S]*?)\*\//);
    if (!headerMatch) return null;
    const header = headerMatch[1] ?? "";
    const tags: Record<string, string> = {};
    for (const m of header.matchAll(tagPattern)) {
        const key = m[1] as string;
        const raw = (m[2] ?? "").replace(/\n[ \t]*\*[ \t]+/g, " ").trim();
        tags[key] = raw;
    }
    if (!tags.stage || !tags.rationale) return null;

    let order = 999;
    if (tags.order !== undefined) {
        const parsed = Number.parseInt(tags.order, 10);
        if (Number.isNaN(parsed)) {
            console.warn(`[extract-stage-rationale] warning: @order "${tags.order}" in ${basename(path)} is not a number - defaulting to 999`);
        } else {
            order = parsed;
        }
    }

    return {
        name: tags.stage,
        rationale: tags.rationale,
        inputs: tags.inputs,
        outputs: tags.outputs,
        order,
        file: `apps/axctl/src/ingest/${basename(path)}`,
    };
};

const main = async () => {
    const files = (await readdir(SRC_DIR))
        .filter((name) => name.endsWith(".ts") && !name.endsWith(".test.ts"))
        .sort();

    const stages: Stage[] = [];
    for (const name of files) {
        const stage = await parseFile(join(SRC_DIR, name));
        if (stage) stages.push(stage);
    }

    if (stages.length === 0) {
        console.error("[extract-stage-rationale] error: no stages found in src/ingest/");
        console.error("  Add @stage and @rationale tags to a leading /** */ JSDoc block in at least one src/ingest/*.ts file.");
        process.exit(2);
    }

    stages.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

    // Escape angle/curly brackets so values like `<repo>/.claude/agents/*.md`
    // aren't parsed as JSX by the MDX compiler downstream (the site build).
    const mdxSafe = (text: string): string =>
        text.replace(/[<>{}]/g, (c) => `&#${c.charCodeAt(0)};`);

    const sections = stages.map((s) => {
        const lines: string[] = [
            `### ${mdxSafe(s.name)}`,
            ``,
            mdxSafe(s.rationale),
            ``,
        ];
        if (s.inputs) lines.push(`**Inputs:** ${mdxSafe(s.inputs)}`, ``);
        if (s.outputs) lines.push(`**Outputs:** ${mdxSafe(s.outputs)}`, ``);
        lines.push(`_Source: \`${s.file}\`_`, ``);
        return lines.join("\n");
    });

    const out = [
        `{/* GENERATED by scripts/extract-stage-rationale.ts - do not edit by hand. */}`,
        `{/* Edit @rationale comments on src/ingest/*.ts instead. */}`,
        ``,
        ...sections,
    ].join("\n");

    await mkdir(dirname(OUT_PATH), { recursive: true });
    await writeFile(OUT_PATH, out, "utf8");
    console.log(`wrote ${stages.length} stage(s) to ${OUT_PATH}`);
};

await main();
