#!/usr/bin/env bun
/**
 * Generate the custom DuckDB library import for a compiled `ax` binary.
 *
 *   bun scripts/gen-duckdb-embed.ts --manifest   # build DuckDB and write manifest
 *   bun scripts/gen-duckdb-embed.ts --stub       # restore the committed stub
 *
 * Both flags are required explicitly - there is no default action - so a bare
 * invocation can never silently overwrite the committed stub.
 *
 * scripts/build-axctl.ts wraps a binary build in writeManifest() -> compile ->
 * writeStub(), mirroring gen-studio-embed.ts / gen-hooks-embed.ts exactly, so
 * the committed copy of apps/axctl/src/duckdb-embed.gen.ts stays the empty
 * stub.
 */
import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const GEN_FILE = join(REPO_ROOT, "apps/axctl/src/duckdb-embed.gen.ts");

const STUB = `// AUTO-GENERATED stub - replaced during a custom DuckDB embed build
// (scripts/build-axctl.ts -> scripts/gen-duckdb-embed.ts writeManifest()),
// then restored to this stub afterwards so source builds and \`bun test\` do
// not require a platform-specific library.
//
// Wiring (#791, wave 3 c-binary-embed): \`packages/lib\` cannot import from
// \`apps/axctl\` (this file), so every apps-side consumer that reads the
// published DuckDB snapshot threads this value in as \`assetPath\` instead of
// reaching for a bare \`DuckDbLive\` - see \`apps/axctl/src/duckdb-embed-wiring.ts\`
// (the shared \`CacheReadLive\` wired via \`CacheReadLayer({ assetPath:
// DUCKDB_DYLIB })\`, and \`duckdbAssetPathOption()\` for the
// \`withCacheWrite\`/\`withConfigWrite\` call sites in
// \`apps/axctl/src/ingest/run.ts\`, \`apps/axctl/src/cli/commands/ingest.ts\`, and
// \`apps/axctl/src/config-core/reconcile.ts\`).
export const DUCKDB_DYLIB: string | undefined = undefined;
`;

/** Restore the empty stub. Defaults to the committed generated file. */
export function writeStub(targetFile: string = GEN_FILE): void {
    writeFileSync(targetFile, STUB);
}

/**
 * Write the embed manifest for an existing platform library.
 * `targetFile` defaults to the committed generated file; tests inject a
 * temp-copy path so they never mutate the real one.
 */
export function writeManifestFromDylib(dylibPath: string, targetFile: string = GEN_FILE): void {
    if (!existsSync(dylibPath)) throw new Error(`DuckDB library not found: ${dylibPath}`);

    let spec = relative(dirname(targetFile), dylibPath).split(/[\\/]/).join("/");
    if (!spec.startsWith(".")) spec = `./${spec}`;

    const manifest = [
        "// AUTO-GENERATED by scripts/gen-duckdb-embed.ts during a binary build.",
        "// Do not edit or commit. Restore the empty stub with --stub.",
        `import duckdbDylib from ${JSON.stringify(spec)} with { type: "file" };`,
        "",
        "export const DUCKDB_DYLIB: string | undefined = duckdbDylib;",
        "",
    ].join("\n");
    writeFileSync(targetFile, manifest);
}

/** Platform-specific library filename, mirroring build-duckdb.sh's `case
 *  $(uname -s)` branch. */
const libraryName = (): string => (process.platform === "darwin" ? "libduckdb.dylib" : "libduckdb.so");

/**
 * The dist dir `scripts/build-duckdb.sh` writes to and reads
 * `DUCKDB_DIST_DIR` from - kept in sync with that script's own
 * `dist_dir=${DUCKDB_DIST_DIR:-"$repo_root/dist/duckdb"}` default so both
 * sides agree on where a provisioned build lives.
 */
export function duckdbDistDir(): string {
    return process.env.DUCKDB_DIST_DIR?.trim() || join(REPO_ROOT, "dist/duckdb");
}

/** Build the custom DuckDB library, then emit its Bun file import. */
export function writeManifest(targetFile: string = GEN_FILE): void {
    const build = spawnSync(join(REPO_ROOT, "scripts/build-duckdb.sh"), [], {
        cwd: REPO_ROOT,
        stdio: "inherit",
    });
    if (build.status !== 0) throw new Error("custom DuckDB build failed");

    const dylibPath = join(duckdbDistDir(), libraryName());
    writeManifestFromDylib(dylibPath, targetFile);
    console.log(`[gen-duckdb-embed] embedded ${dylibPath} → ${targetFile}`);
}

/**
 * `writeManifest()`, but skips the (20-60 minute) `build-duckdb.sh` rebuild
 * when a matching library already sits at `duckdbDistDir()` - the case for
 * every `bun run build` invoked after CI's separate `duckdb` job has already
 * built and downloaded the artifact (or after a developer has run
 * `scripts/build-duckdb.sh` once locally). `build-duckdb.sh` itself always
 * rebuilds unconditionally (a fresh clone + `make`, no dist-dir short
 * circuit), so `scripts/build-axctl.ts` calls THIS, not `writeManifest()`
 * directly, to avoid silently doubling every CI run's wall-clock time by
 * rebuilding an artifact that is already sitting on disk.
 */
export function writeManifestReusingBuild(targetFile: string = GEN_FILE): void {
    const dylibPath = join(duckdbDistDir(), libraryName());
    if (existsSync(dylibPath)) {
        writeManifestFromDylib(dylibPath, targetFile);
        console.log(`[gen-duckdb-embed] reused existing build at ${dylibPath} → ${targetFile}`);
        return;
    }
    writeManifest(targetFile);
}

function printUsage(): void {
    console.error(
        "usage: bun scripts/gen-duckdb-embed.ts --manifest | --stub\n" +
            "  --manifest   build DuckDB and write the embed manifest\n" +
            "  --stub       restore the committed empty stub",
    );
}

if (import.meta.main) {
    const args = process.argv.slice(2);
    if (args.includes("--stub")) writeStub();
    else if (args.includes("--manifest")) writeManifest();
    else {
        printUsage();
        process.exit(1);
    }
}
