#!/usr/bin/env bun
/**
 * Generate the custom DuckDB library import for a compiled `ax` binary.
 *
 *   bun scripts/gen-duckdb-embed.ts          # build DuckDB and write manifest
 *   bun scripts/gen-duckdb-embed.ts --stub   # restore the committed stub
 *
 * A later cutover will connect these functions to scripts/build-axctl.ts.
 */
import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const GEN_FILE = join(REPO_ROOT, "apps/axctl/src/duckdb-embed.gen.ts");

const STUB = `// AUTO-GENERATED stub - replaced during a custom DuckDB embed build, then
// restored so source builds do not require a platform-specific library.
export const DUCKDB_DYLIB: string | undefined = undefined;
`;

export function writeStub(): void {
    writeFileSync(GEN_FILE, STUB);
}

/** Write the embed manifest for an existing platform library. */
export function writeManifestFromDylib(dylibPath: string): void {
    if (!existsSync(dylibPath)) throw new Error(`DuckDB library not found: ${dylibPath}`);

    let spec = relative(dirname(GEN_FILE), dylibPath).split(/[\\/]/).join("/");
    if (!spec.startsWith(".")) spec = `./${spec}`;

    const manifest = [
        "// AUTO-GENERATED by scripts/gen-duckdb-embed.ts during a binary build.",
        "// Do not edit or commit. Restore the empty stub with --stub.",
        `import duckdbDylib from ${JSON.stringify(spec)} with { type: "file" };`,
        "",
        "export const DUCKDB_DYLIB: string | undefined = duckdbDylib;",
        "",
    ].join("\n");
    writeFileSync(GEN_FILE, manifest);
}

/** Build the custom DuckDB library, then emit its Bun file import. */
export function writeManifest(): void {
    const build = spawnSync(join(REPO_ROOT, "scripts/build-duckdb.sh"), [], {
        cwd: REPO_ROOT,
        stdio: "inherit",
    });
    if (build.status !== 0) throw new Error("custom DuckDB build failed");

    const libraryName = process.platform === "darwin" ? "libduckdb.dylib" : "libduckdb.so";
    const dylibPath = join(REPO_ROOT, "dist/duckdb", libraryName);
    writeManifestFromDylib(dylibPath);
    console.log(`[gen-duckdb-embed] embedded ${dylibPath} → ${GEN_FILE}`);
}

if (import.meta.main) {
    if (process.argv.includes("--stub")) writeStub();
    else writeManifest();
}
