#!/usr/bin/env bun
/**
 * Generate the studio embed manifest baked into the compiled `ax` binary.
 *
 * The compiled binary has no source tree, so it cannot read apps/studio/dist
 * off disk. Bun's `bun build --compile` DOES embed any file imported with
 * `{ type: "file" }`, returning a `/$bunfs` path that `Bun.file` can read. So
 * we build the studio daemon target, then emit an `apps/axctl/.../studio-embed.gen.ts`
 * module that imports every asset that way and maps URL path → embedded path.
 *
 *   bun scripts/gen-studio-embed.ts          # build studio + write the real manifest
 *   bun scripts/gen-studio-embed.ts --stub   # restore the committed empty stub
 *
 * build-axctl.ts wraps a binary build in writeManifest() → compile → writeStub()
 * so the committed copy of studio-embed.gen.ts stays the empty stub.
 */
import { spawnSync } from "node:child_process";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative } from "node:path";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const DIST = join(REPO_ROOT, "apps/studio/dist");
const GEN_FILE = join(REPO_ROOT, "apps/axctl/src/dashboard/studio-embed.gen.ts");

const STUB = `// AUTO-GENERATED stub - replaced with the embedded studio assets during the
// binary build (\`bun run build\` → scripts/build-axctl.ts → gen-studio-embed.ts),
// then restored to this stub afterwards so the committed copy stays empty.
//
// Committed empty so a fresh clone, \`tsc\`, and \`bun test\` all resolve this
// module. When the map is empty, \`serveStudioAsset\` falls back to reading the
// studio build off disk (apps/studio/dist) - which is what \`ax serve\` from
// source uses for dogfooding. The compiled binary has no source tree, so its
// build bakes the assets in here via \`{ type: "file" }\` imports instead.
export const STUDIO_EMBED: Record<string, string> = {};
`;

/** Recursively list files under dir, returning posix paths relative to dir. */
function walk(dir: string): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
        const full = join(dir, name);
        if (statSync(full).isDirectory()) {
            out.push(...walk(full).map((p) => `${name}/${p}`));
        } else {
            out.push(name);
        }
    }
    return out;
}

export function writeStub(): void {
    writeFileSync(GEN_FILE, STUB);
}

/** Build the studio daemon target, then emit the embed manifest. */
export function writeManifest(): void {
    const build = spawnSync("bun", ["--filter", "@ax/studio", "build"], {
        stdio: "inherit",
        cwd: REPO_ROOT,
    });
    if (build.status !== 0) throw new Error("studio daemon build failed");

    // Strip sourcemaps (mirrors stage-studio.ts) - they bloat the binary and
    // are never served. Everything else gets embedded.
    const files = walk(DIST)
        .filter((p) => !p.endsWith(".map"))
        .sort();
    if (files.length === 0) throw new Error(`no studio assets found under ${DIST}`);

    // Import specifiers are relative to the GEN file's directory.
    const genDir = join(REPO_ROOT, "apps/axctl/src/dashboard");
    const imports: string[] = [];
    const entries: string[] = [];
    files.forEach((rel, i) => {
        const spec = relative(genDir, join(DIST, rel)).split(/[\\/]/).join("/");
        imports.push(`import a${i} from ${JSON.stringify(spec)} with { type: "file" };`);
        entries.push(`    ${JSON.stringify(`/${rel}`)}: a${i},`);
    });

    const out = [
        "// AUTO-GENERATED by scripts/gen-studio-embed.ts during the binary build.",
        "// Do not edit or commit - the committed copy is an empty stub (see writeStub).",
        ...imports,
        "",
        "export const STUDIO_EMBED: Record<string, string> = {",
        ...entries,
        "};",
        "",
    ].join("\n");
    writeFileSync(GEN_FILE, out);
    console.log(`[gen-studio-embed] wrote ${files.length} embedded studio assets → ${GEN_FILE}`);
}

if (import.meta.main) {
    if (process.argv.includes("--stub")) writeStub();
    else writeManifest();
}
