#!/usr/bin/env bun
/**
 * Generate the custom DuckDB library import for a compiled `ax` binary.
 *
 *   bun scripts/gen-duckdb-embed.ts --manifest   # build DuckDB and write manifest
 *   bun scripts/gen-duckdb-embed.ts --stub       # restore the committed stub
 *
 * Both flags are required explicitly - there is no default action - so a bare
 * invocation can never silently overwrite the committed stub.
 *
 * A later cutover will connect these functions to scripts/build-axctl.ts.
 */
import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const GEN_FILE = join(REPO_ROOT, "apps/axctl/src/duckdb-embed.gen.ts");

const STUB = `// AUTO-GENERATED stub - replaced during a custom DuckDB embed build, then
// restored so source builds do not require a platform-specific library.
export const DUCKDB_DYLIB: string | undefined = undefined;
`;

/** Restore the empty stub. Defaults to the committed generated file. */
export function writeStub(targetFile: string = GEN_FILE): void {
    writeFileSync(targetFile, STUB);
}

/**
 * Write the embed manifest for an existing platform library.
 * `targetFile` defaults to the committed generated file; tests inject a
 * temp-copy path so they never mutate the real one.
 */
export function writeManifestFromDylib(dylibPath: string, targetFile: string = GEN_FILE): void {
    if (!existsSync(dylibPath)) throw new Error(`DuckDB library not found: ${dylibPath}`);

    let spec = relative(dirname(targetFile), dylibPath).split(/[\\/]/).join("/");
    if (!spec.startsWith(".")) spec = `./${spec}`;

    const manifest = [
        "// AUTO-GENERATED by scripts/gen-duckdb-embed.ts during a binary build.",
        "// Do not edit or commit. Restore the empty stub with --stub.",
        `import duckdbDylib from ${JSON.stringify(spec)} with { type: "file" };`,
        "",
        "export const DUCKDB_DYLIB: string | undefined = duckdbDylib;",
        "",
    ].join("\n");
    writeFileSync(targetFile, manifest);
}

/** Build the custom DuckDB library, then emit its Bun file import. */
export function writeManifest(targetFile: string = GEN_FILE): void {
    const build = spawnSync(join(REPO_ROOT, "scripts/build-duckdb.sh"), [], {
        cwd: REPO_ROOT,
        stdio: "inherit",
    });
    if (build.status !== 0) throw new Error("custom DuckDB build failed");

    const libraryName = process.platform === "darwin" ? "libduckdb.dylib" : "libduckdb.so";
    const dylibPath = join(REPO_ROOT, "dist/duckdb", libraryName);
    writeManifestFromDylib(dylibPath, targetFile);
    console.log(`[gen-duckdb-embed] embedded ${dylibPath} → ${targetFile}`);
}

function printUsage(): void {
    console.error(
        "usage: bun scripts/gen-duckdb-embed.ts --manifest | --stub\n" +
            "  --manifest   build DuckDB and write the embed manifest\n" +
            "  --stub       restore the committed empty stub",
    );
}

if (import.meta.main) {
    const args = process.argv.slice(2);
    if (args.includes("--stub")) writeStub();
    else if (args.includes("--manifest")) writeManifest();
    else {
        printUsage();
        process.exit(1);
    }
}
