// scripts/gen-skill-provenance.ts
/**
 * Codegen the skill-provenance registry for the community leaderboard. A skill
 * installed as a loose ~/.claude/skills/ dir loses its origin (ax stamps it
 * `source: local`), so the board can't credit its author. This generator
 * enumerates the skill names shipped by known public collections and emits a
 * `name -> author label` map; the compile applies it as a fallback so those
 * skills badge their author instead of "local".
 *
 * Run: `bun scripts/gen-skill-provenance.ts` (needs an authed `gh` for the
 * GitHub-hosted collections). Output is committed and consumed by
 * `@ax/community-compile`; never hand-edit the generated file.
 *
 * SOURCES is PRIORITY-ORDERED: the first collection to claim a bare name wins,
 * and later collisions are dropped + reported (so a name a specific collection
 * owns isn't stolen by the generic Claude-built-ins list).
 */
import { Glob } from "bun";

const OUT = "packages/community-compile/src/skill-provenance.gen.ts";

type Source =
    | { readonly label: string; readonly repo: string; readonly branch?: string }
    | { readonly label: string; readonly localDir: string }
    | { readonly label: string; readonly names: readonly string[] };

// Priority order: most specific first, generic Claude built-ins last.
const SOURCES: readonly Source[] = [
    { label: "ax", localDir: "skills" },
    { label: "superpowers", repo: "obra/superpowers" },
    { label: "mattpocock", repo: "mattpocock/skills" },
    { label: "composto", names: ["composto"] },
    // Claude Code built-in slash-commands (no public repo to enumerate).
    {
        label: "claude",
        names: [
            "simplify", "code-review", "update-config", "schedule", "loop", "run",
            "init", "verify", "security-review", "fewer-permission-prompts",
            "keybindings-help", "claude-api", "claude-in-chrome",
        ],
    },
];

/** Bare skill names (last path segment of every `**\/SKILL.md`) in a repo. */
function repoSkillNames(repo: string, branch: string): string[] {
    const res = Bun.spawnSync(["gh", "api", `repos/${repo}/git/trees/${branch}?recursive=1`]);
    if (res.exitCode !== 0) throw new Error(`gh api failed for ${repo}@${branch}: ${res.stderr.toString()}`);
    const tree = JSON.parse(res.stdout.toString()) as { tree: Array<{ path: string }> };
    return [
        ...new Set(
            tree.tree
                .filter((t) => t.path.endsWith("/SKILL.md") || t.path === "SKILL.md")
                .map((t) => t.path.replace(/\/SKILL\.md$/, "").replace(/^.*\//, ""))
                .filter((n) => n.length > 0),
        ),
    ];
}

async function localSkillNames(dir: string): Promise<string[]> {
    const names: string[] = [];
    for await (const file of new Glob("*/SKILL.md").scan({ cwd: dir })) {
        names.push(file.replace(/\/SKILL\.md$/, ""));
    }
    return names;
}

async function namesFor(source: Source): Promise<string[]> {
    if ("repo" in source) return repoSkillNames(source.repo, source.branch ?? "main");
    if ("localDir" in source) return localSkillNames(source.localDir);
    return [...source.names];
}

const map: Record<string, string> = {};
const conflicts: Array<{ name: string; kept: string; dropped: string }> = [];

for (const source of SOURCES) {
    const names = await namesFor(source);
    for (const name of names) {
        if (name in map) {
            conflicts.push({ name, kept: map[name]!, dropped: source.label });
            continue;
        }
        map[name] = source.label;
    }
}

const sorted = Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));

const body = `// GENERATED by scripts/gen-skill-provenance.ts - do not edit.
// Maps a canonical skill identity (bare name) to the author/collection that
// ships it, so loosely-installed shared skills can be credited on the board.
// Regenerate: bun scripts/gen-skill-provenance.ts

export const SKILL_PROVENANCE: Record<string, string> = ${JSON.stringify(sorted, null, 4)};
`;

await Bun.write(OUT, body);
console.log(`wrote ${OUT}: ${Object.keys(sorted).length} skills across ${SOURCES.length} sources.`);
if (conflicts.length > 0) {
    console.log(`dropped ${conflicts.length} name conflicts (first source wins):`);
    for (const c of conflicts) console.log(`  ${c.name}: kept ${c.kept}, dropped ${c.dropped}`);
}
