#!/usr/bin/env bun
/**
 * Generate the SDK-hook embed manifest baked into the compiled `ax` binary.
 *
 * The compiled binary has no source tree and can't `bun install` the
 * `@ax/hooks-sdk` workspace, so `ax hooks init` can't scaffold editable `.ts`
 * hooks there (issue #564). Instead we pre-bundle each starter hook into a
 * STANDALONE `.js` (effect inlined, zero external deps) and embed it: Bun's
 * `bun build --compile` bakes in any file imported with `{ type: "file" }`,
 * returning a `/$bunfs` path that `Bun.file` can read at runtime. `ax hooks
 * init` writes those bundles out so they fire as `bun <file>.js` offline.
 *
 *   bun scripts/gen-hooks-embed.ts          # bundle hooks + write the real manifest
 *   bun scripts/gen-hooks-embed.ts --stub   # restore the committed empty stub
 *
 * build-axctl.ts wraps a binary build in writeManifest() → compile → writeStub()
 * so the committed copy of hooks-embed.gen.ts stays the empty stub.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative } from "node:path";
import { GUARD_NAMES, starterHookContent } from "../apps/axctl/src/hooks/guard-names.ts";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const GEN_FILE = join(REPO_ROOT, "apps/axctl/src/hooks/hooks-embed.gen.ts");
// Entry wrappers + bundles live under apps/axctl so the `@ax/hooks-sdk`
// workspace resolves during bundling; gitignored build scratch.
const BUILD_DIR = join(REPO_ROOT, "apps/axctl/.hooks-embed-build");

const STUB = `// AUTO-GENERATED stub - replaced with the embedded, pre-bundled SDK hooks during
// the binary build (\`bun run build\` → scripts/build-axctl.ts → gen-hooks-embed.ts),
// then restored to this stub afterwards so the committed copy stays empty.
//
// Committed empty so a fresh clone, \`tsc\`, and \`bun test\` all resolve this
// module. When the map is empty, \`ax hooks init\` from source scaffolds editable
// \`.ts\` hooks + a \`file:\` dep on packages/hooks-sdk instead. The compiled binary
// has no source tree, so its build bakes a standalone \`.js\` bundle per guard in
// here via \`{ type: "file" }\` imports; \`ax hooks init\` writes those out so hooks
// fire as \`bun <file>.js\` with no node_modules.
//
// Key = guard name (e.g. "route-dispatch"); value = the embedded \`/$bunfs\` path
// of its standalone bundle, readable via \`Bun.file\`.
export const HOOKS_EMBED: Record<string, string> = {};
`;

export function writeStub(): void {
    writeFileSync(GEN_FILE, STUB);
    rmSync(BUILD_DIR, { recursive: true, force: true });
}

/** Bundle each starter hook into a standalone `.js`, then emit the manifest. */
export function writeManifest(): void {
    rmSync(BUILD_DIR, { recursive: true, force: true });
    mkdirSync(BUILD_DIR, { recursive: true });

    const bundles: string[] = [];
    for (const guard of GUARD_NAMES) {
        // Entry wrapper inside apps/axctl so @ax/hooks-sdk resolves.
        const entry = join(BUILD_DIR, `${guard}.entry.ts`);
        writeFileSync(entry, starterHookContent(guard));
        const outfile = join(BUILD_DIR, `${guard}.js`);
        const build = spawnSync(
            "bun",
            ["build", entry, "--target=bun", "--outfile", outfile],
            { cwd: REPO_ROOT, stdio: ["ignore", "ignore", "inherit"] },
        );
        if (build.status !== 0) throw new Error(`bundling hook '${guard}' failed`);
        bundles.push(guard);
    }

    // Import specifiers are relative to the GEN file's directory.
    const genDir = join(REPO_ROOT, "apps/axctl/src/hooks");
    const imports: string[] = [];
    const entries: string[] = [];
    bundles.forEach((guard, i) => {
        const spec = relative(genDir, join(BUILD_DIR, `${guard}.js`)).split(/[\\/]/).join("/");
        imports.push(`import h${i} from ${JSON.stringify(spec)} with { type: "file" };`);
        entries.push(`    ${JSON.stringify(guard)}: h${i},`);
    });

    const out = [
        "// AUTO-GENERATED by scripts/gen-hooks-embed.ts during the binary build.",
        "// Do not edit or commit - the committed copy is an empty stub (see writeStub).",
        ...imports,
        "",
        "export const HOOKS_EMBED: Record<string, string> = {",
        ...entries,
        "};",
        "",
    ].join("\n");
    writeFileSync(GEN_FILE, out);
    console.log(`[gen-hooks-embed] bundled + embedded ${bundles.length} SDK hooks → ${GEN_FILE}`);
}

if (import.meta.main) {
    if (process.argv.includes("--stub")) writeStub();
    else writeManifest();
}
