#!/usr/bin/env bash
# install-dev.sh - install a global `ax-dev` command alongside the stable `ax`.
#
# `ax-dev` runs ax from THIS source checkout (always your current working tree,
# no rebuild) against an isolated data dir, so you can test latest changes
# side-by-side without touching your real graph. The stable `ax` (released
# binary) is left untouched.
#
#   bash scripts/install-dev.sh
#   ax-dev ingest --since=1   # ingest into the dev data dir
#   ax-dev serve              # dev dashboard (full live ingest works - runs from source)
#   ax-dev -v                 # shows git provenance: which sha/branch you're on
#   rm -rf ~/.local/share/ax-dev   # nuke it entirely
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${AXCTL_BIN_DIR:-$HOME/.local/bin}"
SHIM="$BIN_DIR/ax-dev"
DEV_DATA_DIR="${AX_DEV_DATA_DIR:-$HOME/.local/share/ax-dev}"

command -v bun >/dev/null 2>&1 || {
    echo "[ax-dev] bun is required (https://bun.sh)" >&2
    exit 1
}
mkdir -p "$BIN_DIR"

cat >"$SHIM" <<EOF
#!/usr/bin/env bash
# ax-dev - dev build of ax. Runs from source against an isolated data dir.
# Generated by $REPO/scripts/install-dev.sh. Delete anytime; re-run install-dev.sh
# to re-point it at a different checkout.
set -euo pipefail
export AX_DATA_DIR="\${AX_DATA_DIR:-$DEV_DATA_DIR}"
exec bun "$REPO/apps/axctl/src/cli/index.ts" "\$@"
EOF
chmod +x "$SHIM"

echo "[ax-dev] installed $SHIM"
echo "[ax-dev]   source : $REPO/apps/axctl/src/cli/index.ts  (runs your working tree)"
echo "[ax-dev]   data   : $DEV_DATA_DIR  (disposable - rm -rf to nuke)"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "[ax-dev] NOTE: $BIN_DIR is not on PATH - add it so \`ax-dev\` resolves globally" ;;
esac
echo "[ax-dev] next: ax-dev ingest --since=1   # then: ax-dev serve"
