#!/usr/bin/env bash
# install-dev.sh - install a global `ax-dev` command alongside the stable `ax`.
#
# `ax-dev` runs ax from THIS source checkout (always your current working tree,
# no rebuild) against an isolated, disposable DB (port 8522, ~/.local/share/ax-dev).
# The stable `ax` (released binary, prod DB on 8521) is left untouched, so you can
# test latest changes side-by-side without clobbering your real graph.
#
#   bash scripts/install-dev.sh
#   ax-dev db            # start the disposable dev SurrealDB
#   ax-dev ingest        # ingest into the dev DB
#   ax-dev serve         # dev dashboard
#   ax-dev db --reset    # wipe + restart the dev DB
#   rm -rf ~/.local/share/ax-dev   # nuke it entirely
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${AXCTL_BIN_DIR:-$HOME/.local/bin}"
SHIM="$BIN_DIR/ax-dev"
DEV_DATA_DIR="${AX_DEV_DATA_DIR:-$HOME/.local/share/ax-dev}"
DEV_DB_URL="${AX_DEV_DB_URL:-ws://127.0.0.1:8522}"

command -v bun >/dev/null 2>&1 || {
    echo "[ax-dev] bun is required (https://bun.sh)" >&2
    exit 1
}
mkdir -p "$BIN_DIR"

cat >"$SHIM" <<EOF
#!/usr/bin/env bash
# ax-dev - disposable dev build of ax. Runs from source against an isolated DB.
# Generated by $REPO/scripts/install-dev.sh. Delete anytime; re-run install-dev.sh
# to re-point it at a different checkout.
set -euo pipefail
export AX_DATA_DIR="\${AX_DATA_DIR:-$DEV_DATA_DIR}"
export AX_DB_URL="\${AX_DB_URL:-$DEV_DB_URL}"

# \`ax-dev db [start|--reset|stop|status]\` manages the disposable dev SurrealDB (no launchd).
if [ "\${1:-}" = "db" ]; then
    shift
    exec bash "$REPO/scripts/dev-db.sh" "\$@"
fi
exec bun "$REPO/apps/axctl/src/cli/index.ts" "\$@"
EOF
chmod +x "$SHIM"

echo "[ax-dev] installed $SHIM"
echo "[ax-dev]   source : $REPO/apps/axctl/src/cli/index.ts  (runs your working tree)"
echo "[ax-dev]   data   : $DEV_DATA_DIR  (disposable - rm -rf to nuke)"
echo "[ax-dev]   db url : $DEV_DB_URL  (separate SurrealDB; stable ax stays on :8521)"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "[ax-dev] NOTE: $BIN_DIR is not on PATH - add it so \`ax-dev\` resolves globally" ;;
esac
echo "[ax-dev] next: ax-dev db   # start the dev DB, then: ax-dev ingest / ax-dev serve"
