import { createFileRoute, Link } from "@tanstack/react-router";
import { allChangelogs, allReleaseAnnouncements } from "content-collections";
import { MarkdownLite } from "~/components/release-markdown";
import { SiteFooter } from "~/components/landing-sections/site-footer";
import { SiteHeader } from "~/components/landing-sections/site-header";

export const Route = createFileRoute("/changelog")({
  head: () => ({
    meta: [
      { title: "Changelog - ax" },
      { name: "description", content: "Release announcements and generated changelog entries for ax." },
    ],
  }),
  loader: () => ({
    announcements: [...allReleaseAnnouncements].sort((a, b) => b.date.localeCompare(a.date)),
    changelog: allChangelogs[0] ?? null,
  }),
  component: ChangelogPage,
});

function ChangelogPage() {
  const { announcements, changelog } = Route.useLoaderData();
  const latest = announcements[0];
  const previousAnnouncements = latest
    ? announcements.filter((release) => release.version !== latest.version)
    : announcements;

  // Source of truth for "what shipped last" is the Release Please changelog,
  // not the hand-written announcement layer (which is curated and can lag).
  // Pull the newest version + date straight off the top of CHANGELOG.md so
  // the page always reflects the real latest release.
  const latestRelease = (() => {
    const m = changelog?.content.match(
      /##\s*\[?(\d+\.\d+\.\d+)\]?[^\n]*?\((\d{4}-\d{2}-\d{2})\)/,
    );
    return m ? { version: m[1], date: m[2] } : null;
  })();

  return (
    <>
      <SiteHeader />
      <main className="release-page">
        <section className="release-hero">
          <p className="eyebrow">release notes</p>
          <h1>
            Changes with <em>context</em>.
          </h1>
          <p className="lede">
            Release Please keeps the generated changelog factual. The
            announcement layer explains what changed in product language.
          </p>
          {latestRelease ? (
            <p className="release-latest">
              <span className="release-latest-tag">latest release</span>
              <a href="#generated">
                <b>v{latestRelease.version}</b>
                <span className="release-latest-date">{latestRelease.date}</span>
              </a>
            </p>
          ) : null}
          <div className="release-actions">
            <a href="#announcements">Announcements</a>
            <a href="#generated">Generated changelog</a>
          </div>
        </section>

        <section id="announcements" className="release-section">
          <div className="section-kicker">in-depth announcements</div>
          {latest ? (
            <article className="release-feature">
              <div className="release-meta">
                <span>v{latest.version}</span>
                <span>{latest.date}</span>
              </div>
              <h2>{latest.title}</h2>
              <p>{latest.summary}</p>
              <Link to="/changelog/$version" params={{ version: `v${latest.version}` }} className="release-anchor">
                Latest announcement
              </Link>
            </article>
          ) : (
            <p className="muted">No release announcements have been published yet.</p>
          )}

          {previousAnnouncements.length > 0 ? (
            <div className="release-list">
              {previousAnnouncements.map((release) => (
                <article id={`v${release.version}`} key={release.version} className="release-entry">
                  <div className="release-meta">
                    <span>v{release.version}</span>
                    <span>{release.date}</span>
                  </div>
                  <h3>{release.title}</h3>
                  <p className="release-summary">{release.summary}</p>
                  <Link to="/changelog/$version" params={{ version: `v${release.version}` }} className="release-entry-link">
                    Open release page
                  </Link>
                  <div className="release-body">
                    <MarkdownLite content={release.content} />
                  </div>
                </article>
              ))}
            </div>
          ) : null}
        </section>

        <section id="generated" className="release-section">
          <div className="section-kicker">every release · generated by release please</div>
          <details className="generated-changelog" open>
            <summary>
              <span>Full generated changelog</span>
              <small>commit-level detail for every version</small>
            </summary>
            <article>
              {changelog ? (
                <MarkdownLite content={changelog.content} />
              ) : (
                <p className="muted">CHANGELOG.md has not been generated yet.</p>
              )}
            </article>
          </details>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
