import { createFileRoute, notFound, Link } from "@tanstack/react-router";
import {
  allChangelogs,
  allReleaseAnnouncements,
  type ReleaseAnnouncement,
} from "content-collections";
import { SiteFooter } from "~/components/landing-sections/site-footer";
import { SiteHeader } from "~/components/landing-sections/site-header";
import { MarkdownInline, MarkdownLite } from "~/components/release-markdown";

type ReleaseLoaderData = {
  release: ReleaseAnnouncement;
  generatedEntry: string | null;
  generatedSections: GeneratedSection[];
};

function loadRelease({ params }: { params: { version: string } }): ReleaseLoaderData {
  const normalized = params.version.replace(/^v/, "");
  const release = allReleaseAnnouncements.find((item) => item.version === normalized);
  if (!release) throw notFound();
  const changelog = allChangelogs[0]?.content ?? "";
  const generatedEntry = extractGeneratedEntry(changelog, normalized);
  return {
    release,
    generatedEntry,
    generatedSections: parseGeneratedSections(generatedEntry),
  };
}

export const Route = createFileRoute("/changelog_/$version")({
  head: ({ loaderData }) => {
    const data = loaderData as ReleaseLoaderData | undefined;
    return {
      meta: data
        ? [
            { title: `${data.release.title} - ax v${data.release.version}` },
            { name: "description", content: data.release.summary },
          ]
        : [
            { title: "Release not found - ax" },
          ],
    };
  },
  loader: loadRelease,
  component: ReleasePage,
});

function ReleasePage() {
  const { release, generatedEntry, generatedSections } = Route.useLoaderData() as ReleaseLoaderData;
  const itemCount = generatedSections.reduce((sum, section) => sum + section.items.length, 0);

  return (
    <>
      <SiteHeader />
      <main className="release-page release-detail-page">
        <section className="release-hero">
          <p className="eyebrow">release v{release.version}</p>
          <h1>{release.title}</h1>
          <p className="lede">{release.summary}</p>
          <div className="release-meta">
            <span>{release.date}</span>
            <span>ax v{release.version}</span>
            {itemCount > 0 ? <span>{itemCount} referenced changes</span> : null}
          </div>
          <div className="release-actions">
            <Link to="/changelog">All releases</Link>
            <a href="#referenced">Referenced changes</a>
            <a href="#generated">Generated changelog</a>
          </div>
        </section>

        <section className="release-section">
          <div className="section-kicker">announcement</div>
          <article className="release-detail-body">
            <MarkdownLite content={release.content} />
          </article>
        </section>

        {generatedSections.length > 0 ? (
          <section id="referenced" className="release-section release-reference">
            <div className="section-kicker">referenced changes</div>
            <div className="release-reference-head">
              <h2>{itemCount} linked changes</h2>
              <p>
                Generated from Release Please and grouped by change type. Each row
                keeps its issue and commit references.
              </p>
            </div>
            <div className="release-reference-nav">
              {generatedSections.map((section) => (
                <a key={section.slug} href={`#${section.slug}`}>
                  {section.title} <span>{section.items.length}</span>
                </a>
              ))}
            </div>
            <div className="release-reference-groups">
              {generatedSections.map((section) => (
                <article id={section.slug} key={section.slug} className="release-reference-group">
                  <h3>{section.title}</h3>
                  <ol className="release-change-list">
                    {section.items.map((item, index) => (
                      <li key={`${section.slug}-${index}`}>
                        <span className="release-change-index">{String(index + 1).padStart(2, "0")}</span>
                        <span className="release-change-text">
                          <MarkdownInline text={item.text} />
                        </span>
                      </li>
                    ))}
                  </ol>
                </article>
              ))}
            </div>
          </section>
        ) : null}

        <section id="generated" className="release-section">
          <div className="section-kicker">generated by release please</div>
          <details className="generated-changelog">
            <summary>
              <span>Show generated changelog for v{release.version}</span>
              <small>commit-level detail from Release Please</small>
            </summary>
            <article>
              {generatedEntry ? (
                <MarkdownLite content={generatedEntry} />
              ) : (
                <p className="muted">No generated changelog entry found for this version.</p>
              )}
            </article>
          </details>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}

function extractGeneratedEntry(changelog: string, version: string): string | null {
  const escaped = version.replace(/\./g, "\\.");
  const heading = new RegExp(`^## \\[?${escaped}\\]?.*$`, "m");
  const match = changelog.match(heading);
  if (!match || match.index === undefined) return null;
  const rest = changelog.slice(match.index);
  const next = rest.slice(match[0].length).search(/^## /m);
  return next >= 0
    ? rest.slice(0, match[0].length + next).trim()
    : rest.trim();
}

type GeneratedSection = {
  title: string;
  slug: string;
  items: Array<{ text: string }>;
};

function parseGeneratedSections(content: string | null): GeneratedSection[] {
  if (!content) return [];
  const sections: GeneratedSection[] = [];
  let current: GeneratedSection | null = null;

  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (line.startsWith("### ")) {
      const title = line.slice(4).trim();
      current = {
        title,
        slug: `release-${slugify(title)}`,
        items: [],
      };
      sections.push(current);
      continue;
    }

    if (current && line.startsWith("* ")) {
      current.items.push({ text: line.slice(2).trim() });
    }
  }

  return sections.filter((section) => section.items.length > 0);
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
