import { describe, expect, test } from "bun:test";
import { SkillName } from "@ax/lib/brands";
import { agentEventRecordKey } from "./provider-events.ts";
import { fileRecordKey, toolCallRecordKey, turnRecordKey } from "./record-keys.ts";
import { extractToolFileEvidence } from "./tool-file-evidence.ts";
import {
    __testExtractClaudeJsonlLines,
    buildClaudeTokenUsageStatements,
    buildClaudeTurnTokenUsageStatements,
    claudeConcurrency,
    transcriptEditFileRecordKey,
} from "./transcripts.ts";

// Fixture skill names are plain string literals; brand via the schema constructor.
const sn = (s: string): SkillName => SkillName.make(s);

describe("Claude transcript extraction", () => {
    test("claudeConcurrency rejects invalid values", () => {
        expect(claudeConcurrency(undefined)).toBe(4);
        expect(claudeConcurrency("8")).toBe(8);
        expect(claudeConcurrency("0")).toBe(4);
        expect(claudeConcurrency("nope")).toBe(4);
    });

    test("extracts plain user prompts and classifies context versus tool-result turns", () => {
        const longTaskText = `Find the files that define transcript ingest.\n${"x".repeat(620)}`;
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:00.000Z",
                    message: {
                        role: "user",
                        content: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:01.000Z",
                    message: {
                        role: "user",
                        content: longTaskText,
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:02.000Z",
                    message: {
                        role: "user",
                        content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:03.000Z",
                    message: {
                        role: "user",
                        content: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:04.000Z",
                    message: {
                        role: "user",
                        content: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:05.000Z",
                    message: {
                        role: "user",
                        content: [
                            {
                                type: "tool_result",
                                tool_use_id: "toolu_read",
                                content: "src/ingest/transcripts.ts",
                            },
                        ],
                    },
                }),
            ],
            "-tmp-project",
            "claude-user-text",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(
            extracted.turns.map((turn) => ({
                role: turn.role,
                text: turn.text,
                text_excerpt: turn.text_excerpt,
                message_kind: turn.message_kind,
                intent_kind: turn.intent_kind,
            })),
        ).toEqual([
            {
                role: "user",
                text: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                text_excerpt: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
                message_kind: "context",
                intent_kind: "system_context",
            },
            {
                role: "user",
                text: longTaskText,
                text_excerpt: longTaskText.slice(0, 500),
                message_kind: "task",
                intent_kind: "organic_task",
            },
            {
                role: "user",
                text: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                text_excerpt: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
                message_kind: "context",
                intent_kind: "system_context",
            },
            {
                role: "user",
                text: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                text_excerpt: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
                message_kind: "context",
                intent_kind: "skill_context",
            },
            {
                role: "user",
                text: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                text_excerpt: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
                message_kind: "control",
                intent_kind: "control",
            },
            {
                role: "user",
                text: null,
                text_excerpt: null,
                message_kind: "tool_result",
                intent_kind: "tool_result",
            },
        ]);
        expect(extracted.providerEvents.map((event) => ({
            provider: event.provider,
            providerSessionId: event.providerSessionId,
            seq: event.seq,
            type: event.type,
            role: event.role,
            textExcerpt: event.textExcerpt,
        }))).toEqual([
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 1,
                type: "user",
                role: "user",
                textExcerpt: "# AGENTS.md instructions for /tmp/project\n\n<INSTRUCTIONS>Use Bun.</INSTRUCTIONS>",
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 2,
                type: "user",
                role: "user",
                textExcerpt: longTaskText.slice(0, 500),
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 3,
                type: "user",
                role: "user",
                textExcerpt: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 4,
                type: "user",
                role: "user",
                textExcerpt: "Base directory for this skill: /Users/necmttn/.claude/skills/example\n\n# Skill instructions",
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 5,
                type: "user",
                role: "user",
                textExcerpt: "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 6,
                type: "user",
                role: "user",
                textExcerpt: null,
            },
            {
                provider: "claude",
                providerSessionId: "claude-user-text",
                seq: 7,
                type: "tool_result",
                role: "user",
                textExcerpt: "src/ingest/transcripts.ts",
            },
        ]);
    });

    test("invocations carry seq as turn_index", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_s1",
                                name: "Skill",
                                input: { skill: "composto" },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:01.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_s2",
                                name: "Skill",
                                input: { skill: "composto" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-turn-index",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.invocations).toHaveLength(2);
        // First assistant turn → seq=1; second → seq=2
        expect(extracted.invocations[0]!.seq).toBe(1);
        expect(extracted.invocations[1]!.seq).toBe(2);
        // The seq value on invocations is what gets written as turn_index on the edge.
    });

    test("extracts tool calls, tool results, skill relations, edits, and TodoWrite snapshots", () => {
        const longOutput = `${"x".repeat(1600)}\nfinal line`;
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_skill",
                                name: "Skill",
                                input: {
                                    skill: "superpowers:test-driven-development",
                                    reason: "Need TDD",
                                },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_bash",
                                name: "Bash",
                                input: {
                                    command: "cd src && bun test src/ingest/transcripts.test.ts",
                                },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_edit",
                                name: "Edit",
                                input: {
                                    file_path: "src/ingest/transcripts.ts",
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T10:00:01.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_result",
                                tool_use_id: "toolu_bash",
                                is_error: true,
                                content: longOutput,
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:02.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_1",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect schema",
                                            activeForm: "Inspecting schema",
                                            status: "completed",
                                        },
                                        {
                                            content: "Wire writers",
                                            activeForm: "Wiring writers",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:03.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_2",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect schema",
                                            activeForm: "Inspecting schema",
                                            status: "completed",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-abc",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.toolCalls).toHaveLength(5);
        expect(extracted.edits).toEqual([
            {
                session: "session-abc",
                seq: 1,
                ts: "2026-05-09T10:00:00.000Z",
                repo: "ax",
                path: "/Users/necmttn/Projects/ax/src/ingest/transcripts.ts",
                tool: "Edit",
            },
        ]);

        const skillCall = extracted.toolCalls.find((call) => call.toolName === "Skill");
        expect(skillCall).toMatchObject({
            provider: "claude",
            toolKind: "skill",
            sessionId: "session-abc",
            seq: 1,
            turnKey: turnRecordKey("session-abc", 1),
            callId: "toolu_skill",
            cwd: "/Users/necmttn/Projects/ax",
            hasError: false,
        });
        expect(skillCall?.inputJson).toEqual({
            skill: "superpowers:test-driven-development",
            reason: "Need TDD",
        });
        expect(skillCall?.rawJson).toMatchObject({
            type: "tool_use",
            id: "toolu_skill",
            name: "Skill",
        });
        expect(skillCall?.agentEventKey).toBe(agentEventRecordKey({
            provider: "claude",
            providerSessionId: "session-abc",
            providerEventId: "toolu_skill",
            seq: 2,
        }));

        const bashCall = extracted.toolCalls.find((call) => call.toolName === "Bash");
        expect(bashCall).toMatchObject({
            provider: "claude",
            toolKind: "builtin",
            sessionId: "session-abc",
            seq: 1,
            turnKey: turnRecordKey("session-abc", 1),
            callId: "toolu_bash",
            commandText: "cd src && bun test src/ingest/transcripts.test.ts",
            commandToolName: "bun",
            commandNorm: "bun test",
            hasError: true,
        });
        expect(typeof bashCall?.errorText).toBe("string");
        expect(bashCall?.outputJson).toBe(longOutput);
        expect(bashCall?.outputExcerpt?.length).toBeLessThanOrEqual(1200);
        expect(bashCall?.outputExcerpt).toBe(bashCall?.errorText);
        expect(bashCall?.agentEventKey).toBe(agentEventRecordKey({
            provider: "claude",
            providerSessionId: "session-abc",
            providerEventId: "toolu_bash",
            seq: 3,
        }));
        expect(extracted.providerEvents.map((event) => ({
            providerEventId: event.providerEventId,
            seq: event.seq,
            type: event.type,
            role: event.role,
            textExcerpt: event.textExcerpt,
        }))).toEqual([
            {
                providerEventId: null,
                seq: 1,
                type: "assistant",
                role: "assistant",
                textExcerpt: null,
            },
            {
                providerEventId: "toolu_skill",
                seq: 2,
                type: "tool_use",
                role: "assistant",
                textExcerpt: "Skill",
            },
            {
                providerEventId: "toolu_bash",
                seq: 3,
                type: "tool_use",
                role: "assistant",
                textExcerpt: "Bash",
            },
            {
                providerEventId: "toolu_edit",
                seq: 4,
                type: "tool_use",
                role: "assistant",
                textExcerpt: "Edit",
            },
            {
                providerEventId: null,
                seq: 5,
                type: "user",
                role: "user",
                textExcerpt: null,
            },
            {
                providerEventId: "tool_result:toolu_bash",
                seq: 6,
                type: "tool_result",
                role: "user",
                textExcerpt: longOutput.slice(0, 500),
            },
            {
                providerEventId: null,
                seq: 7,
                type: "assistant",
                role: "assistant",
                textExcerpt: null,
            },
            {
                providerEventId: "toolu_todo_1",
                seq: 8,
                type: "tool_use",
                role: "assistant",
                textExcerpt: "TodoWrite",
            },
            {
                providerEventId: null,
                seq: 9,
                type: "assistant",
                role: "assistant",
                textExcerpt: null,
            },
            {
                providerEventId: "toolu_todo_2",
                seq: 10,
                type: "tool_use",
                role: "assistant",
                textExcerpt: "TodoWrite",
            },
        ]);

        expect(extracted.skillRelations).toEqual([
            {
                toolCallKey: toolCallRecordKey({
                    sessionId: "session-abc",
                    seq: 1,
                    callId: "toolu_skill",
                }),
                skillName: sn("superpowers:test-driven-development"),
                ts: "2026-05-09T10:00:00.000Z",
                reason: "Claude Skill tool invocation",
                labels: { provider: "claude", toolName: "Skill", source: "transcript" },
                metrics: { turnSeq: 1 },
            },
        ]);

        expect(extracted.planSnapshots).toHaveLength(2);
        const [firstSnapshot, secondSnapshot] = extracted.planSnapshots;
        expect(firstSnapshot).toMatchObject({
            sessionId: "session-abc",
            source: "claude_todowrite",
            status: "in_progress",
            createdAt: "2026-05-09T10:00:02.000Z",
            updatedAt: "2026-05-09T10:00:02.000Z",
            ts: "2026-05-09T10:00:02.000Z",
            toolCallKey: toolCallRecordKey({
                sessionId: "session-abc",
                seq: 3,
                callId: "toolu_todo_1",
            }),
        });
        expect(firstSnapshot.items).toEqual([
            expect.objectContaining({
                seq: 1,
                content: "Inspect schema",
                activeForm: "Inspecting schema",
                status: "completed",
            }),
            expect.objectContaining({
                seq: 2,
                content: "Wire writers",
                activeForm: "Wiring writers",
                status: "in_progress",
            }),
        ]);
        expect(secondSnapshot.planKey).toBe(firstSnapshot.planKey);
        expect(secondSnapshot.createdAt).toBe("2026-05-09T10:00:02.000Z");
        expect(secondSnapshot.updatedAt).toBe("2026-05-09T10:00:03.000Z");
        expect(secondSnapshot.snapshotKey).not.toBe(firstSnapshot.snapshotKey);
    });

    test("assigns stable fallback ids to anonymous tool uses in the same turn", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T11:00:00.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                name: "Bash",
                                input: { command: "pwd" },
                            },
                            {
                                type: "tool_use",
                                name: "Bash",
                                input: { command: "git status --short" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-anonymous",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.toolCalls.map((call) => call.callId)).toEqual([
            "anonymous_tool_use_000001_001",
            "anonymous_tool_use_000001_002",
        ]);
        expect(
            new Set(
                extracted.toolCalls.map((call) =>
                    toolCallRecordKey({
                        sessionId: call.sessionId,
                        seq: call.seq,
                        callId: call.callId ?? null,
                    }),
                ),
            ).size,
        ).toBe(2);
    });

    test("assigns unique provider event seqs and links tool calls to their tool_use events", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T11:30:00.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_first",
                                name: "Bash",
                                input: { command: "pwd" },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_second",
                                name: "Read",
                                input: { file_path: "src/ingest/transcripts.ts" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-provider-seq",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        const providerSeqs = extracted.providerEvents.map((event) => event.seq);
        expect(new Set(providerSeqs).size).toBe(providerSeqs.length);

        for (const call of extracted.toolCalls) {
            const providerEventId = call.callId ?? null;
            const event = extracted.providerEvents.find(
                (providerEvent) => providerEvent.providerEventId === providerEventId,
            );
            expect(event).toBeDefined();
            if (!event) continue;
            expect(call.seq).toBe(1);
            expect(call.agentEventKey).toBe(agentEventRecordKey({
                provider: "claude",
                providerSessionId: "session-provider-seq",
                providerEventId,
                seq: event.seq,
            }));
        }
    });

    test("links adjacent transcript provider events with linear parent edges", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    uuid: "claude-user-1",
                    timestamp: "2026-05-09T11:40:00.000Z",
                    message: { role: "user", content: "First prompt." },
                }),
                JSON.stringify({
                    type: "assistant",
                    uuid: "claude-assistant-1",
                    timestamp: "2026-05-09T11:40:01.000Z",
                    message: { role: "assistant", content: "First answer." },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-linear-claude",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.providerEvents.map((event) => ({
            providerEventId: event.providerEventId,
            parentProviderEventId: event.parentProviderEventId,
            parentProviderEventIds: event.parentProviderEventIds,
        }))).toEqual([
            {
                providerEventId: "claude-user-1",
                parentProviderEventId: undefined,
                parentProviderEventIds: undefined,
            },
            {
                providerEventId: "claude-assistant-1",
                parentProviderEventId: "claude-user-1",
                parentProviderEventIds: undefined,
            },
        ]);
    });

    test("turn IDs use centralized turnRecordKey format", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_bash",
                                name: "Bash",
                                input: { command: "pwd" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-id-check",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        const expectedTurnKey = turnRecordKey("session-id-check", 1);
        const bashCall = extracted.toolCalls.find((c) => c.toolName === "Bash");
        expect(bashCall?.turnKey).toBe(expectedTurnKey);
    });

    test("edited-file IDs use local path identity before repository canonicalization", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_check",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/Projects/ax/src/a.ts" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-file-check",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        const expectedFileKey = fileRecordKey("_", "/Users/necmttn/Projects/ax/src/a.ts");
        expect(extracted.edits).toHaveLength(1);
        const edit = extracted.edits[0];
        expect(transcriptEditFileRecordKey(edit?.path ?? "")).toBe(expectedFileKey);
    });

    test("Claude tool calls project shared edit read and search file evidence", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit",
                                name: "Edit",
                                input: { file_path: "src/edit.ts" },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_read",
                                name: "Read",
                                input: { file_path: "src/read.ts" },
                            },
                            {
                                type: "tool_use",
                                id: "toolu_grep",
                                name: "Grep",
                                input: { pattern: "needle", path: "src" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "session-shared-file-evidence",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extractToolFileEvidence(extracted.toolCalls).map((item) => ({
            kind: item.kind,
            toolName: item.toolName,
            path: item.path,
            pathSeen: item.pathSeen,
        }))).toEqual([
            {
                kind: "edited",
                toolName: "Edit",
                path: "/Users/necmttn/Projects/ax/src/edit.ts",
                pathSeen: "src/edit.ts",
            },
            {
                kind: "read_file",
                toolName: "Read",
                path: "/Users/necmttn/Projects/ax/src/read.ts",
                pathSeen: "src/read.ts",
            },
            {
                kind: "searched_file",
                toolName: "Grep",
                path: "/Users/necmttn/Projects/ax/src",
                pathSeen: "src",
            },
        ]);
    });

    test("edited-file IDs merge the same local file across cwd-derived repo labels", () => {
        const first = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/apps",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_apps",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/.claude/hooks/block-em-dash.sh" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-apps",
            "session-file-apps",
        );
        const second = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T10:00:00.000Z",
                    cwd: "/Users/necmttn/Projects/myapp",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit_myapp",
                                name: "Edit",
                                input: { file_path: "/Users/necmttn/.claude/hooks/block-em-dash.sh" },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-myapp",
            "session-file-myapp",
        );

        expect(first?.edits[0]?.repo).toBe("apps");
        expect(second?.edits[0]?.repo).toBe("myapp");
        expect(transcriptEditFileRecordKey(first?.edits[0]?.path ?? ""))
            .toBe(transcriptEditFileRecordKey(second?.edits[0]?.path ?? ""));
    });

    test("keeps TodoWrite plan item keys stable when the same sequence changes", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T12:00:00.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_1",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Inspect failing ingest",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T12:00:01.000Z",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_todo_2",
                                name: "TodoWrite",
                                input: {
                                    todos: [
                                        {
                                            content: "Fix plan item identity",
                                            status: "in_progress",
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "claude-plan-session",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.planSnapshots).toHaveLength(2);
        expect(extracted.planSnapshots[0]?.items[0]?.key).toBe(
            extracted.planSnapshots[1]?.items[0]?.key,
        );
    });

    test("extracts native Claude hook events and command invocation outcomes", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-19T07:38:28.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                    message: {
                        content: [
                            {
                                type: "tool_use",
                                id: "toolu_edit",
                                name: "Edit",
                                input: { file_path: "src/a.ts" },
                            },
                        ],
                    },
                }),
                JSON.stringify({
                    type: "progress",
                    data: {
                        type: "hook_progress",
                        hookEvent: "PreToolUse",
                        hookName: "PreToolUse:Edit",
                        command: "bash \"/Users/necmttn/.claude/hooks/block-em-dash.sh\"",
                    },
                    toolUseID: "toolu_edit",
                    uuid: "progress-uuid",
                    timestamp: "2026-05-19T07:38:28.100Z",
                    cwd: "/Users/necmttn/Projects/ax",
                }),
                JSON.stringify({
                    attachment: {
                        type: "hook_success",
                        hookName: "PreToolUse:Edit",
                        toolUseID: "toolu_edit",
                        hookEvent: "PreToolUse",
                        stdout: "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"allow\"}}",
                        stderr: "",
                        exitCode: 0,
                        command: "bash \"/Users/necmttn/.claude/hooks/block-em-dash.sh\"",
                        durationMs: 34,
                    },
                    type: "attachment",
                    uuid: "success-uuid",
                    timestamp: "2026-05-19T07:38:28.170Z",
                    cwd: "/Users/necmttn/Projects/ax",
                }),
                JSON.stringify({
                    attachment: {
                        type: "hook_success",
                        hookName: "PreToolUse:Edit",
                        toolUseID: "toolu_edit",
                        hookEvent: "PreToolUse",
                        stdout: "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"additionalContext\":\"<ax_file_memory>...</ax_file_memory>\"}}",
                        stderr: "",
                        exitCode: 0,
                        command: "axctl hook file-context --format claude",
                        durationMs: 198,
                    },
                    type: "attachment",
                    uuid: "context-uuid",
                    timestamp: "2026-05-19T07:38:28.334Z",
                    cwd: "/Users/necmttn/Projects/ax",
                }),
                JSON.stringify({
                    attachment: {
                        type: "hook_additional_context",
                        content: ["<ax_file_memory>...</ax_file_memory>"],
                        hookName: "PreToolUse:Edit",
                        toolUseID: "toolu_edit",
                        hookEvent: "PreToolUse",
                    },
                    type: "attachment",
                    uuid: "additional-context-uuid",
                    timestamp: "2026-05-19T07:38:28.334Z",
                    cwd: "/Users/necmttn/Projects/ax",
                }),
                JSON.stringify({
                    attachment: {
                        type: "hook_blocking_error",
                        hookName: "PostToolUse:Edit",
                        toolUseID: "toolu_edit",
                        hookEvent: "PostToolUse",
                        blockingError: {
                            command: "bash \"$CLAUDE_PROJECT_DIR/.claude/hooks/oxlint-file.sh\"",
                            blockingError: "Found 1 warning and 0 errors.",
                        },
                    },
                    type: "attachment",
                    uuid: "blocking-uuid",
                    timestamp: "2026-05-19T07:38:29.000Z",
                    cwd: "/Users/necmttn/Projects/ax",
                }),
            ],
            "-Users-necmttn-Projects-ax",
            "claude-hook-session",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.hookEvents.map((event) => ({
            event_name: event.event_name,
            hook_name: event.hook_name,
            tool_call_id: event.tool_call_id,
            tool_call_key: event.tool_call_key,
        }))).toEqual([
            {
                event_name: "PreToolUse",
                hook_name: "PreToolUse:Edit",
                tool_call_id: "toolu_edit",
                tool_call_key: toolCallRecordKey({
                    sessionId: "claude-hook-session",
                    seq: 1,
                    callId: "toolu_edit",
                }),
            },
            {
                event_name: "PostToolUse",
                hook_name: "PostToolUse:Edit",
                tool_call_id: "toolu_edit",
                tool_call_key: toolCallRecordKey({
                    sessionId: "claude-hook-session",
                    seq: 1,
                    callId: "toolu_edit",
                }),
            },
        ]);
        expect(extracted.hookCommandInvocations.map((invocation) => ({
            command: invocation.command,
            provider_status: invocation.provider_status,
            effect: invocation.effect,
            duration_ms: invocation.duration_ms,
            blocking_error_excerpt: invocation.blocking_error_excerpt,
        }))).toEqual([
            {
                command: "bash \"/Users/necmttn/.claude/hooks/block-em-dash.sh\"",
                provider_status: "success",
                effect: "allowed",
                duration_ms: 34,
                blocking_error_excerpt: null,
            },
            {
                command: "axctl hook file-context --format claude",
                provider_status: "success",
                effect: "injected_context",
                duration_ms: 198,
                blocking_error_excerpt: null,
            },
            {
                command: "bash \"$CLAUDE_PROJECT_DIR/.claude/hooks/oxlint-file.sh\"",
                provider_status: "blocking_error",
                effect: "blocked",
                duration_ms: null,
                blocking_error_excerpt: "Found 1 warning and 0 errors.",
            },
        ]);
    });
});

describe("claude compaction", () => {
    test("isCompactSummary message becomes a compaction row, not a user turn", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    uuid: "u1",
                    timestamp: "2026-06-01T10:00:00.000Z",
                    sessionId: "cl-1",
                    cwd: "/tmp",
                    message: { role: "user", content: "real question" },
                }),
                JSON.stringify({
                    type: "user",
                    uuid: "u2",
                    timestamp: "2026-06-01T10:05:00.000Z",
                    sessionId: "cl-1",
                    cwd: "/tmp",
                    isCompactSummary: true,
                    isVisibleInTranscriptOnly: true,
                    message: { role: "user", content: "## Summary\nGoal: ship X" },
                }),
            ],
            "-tmp",
            "cl-1",
        );

        expect(extracted).not.toBeNull();
        if (!extracted) return;

        expect(extracted.compactions.length).toBe(1);
        expect(extracted.compactions[0].strategy).toBe("summarize");
        expect(extracted.compactions[0].summary).toContain("Goal: ship X");
        expect(extracted.compactions[0].boundaryRef).toBe("u2");

        const userTurnTexts = extracted.turns
            .filter((t) => t.role === "user")
            .map((t) => t.text);
        expect(userTurnTexts).toContain("real question");
        expect(userTurnTexts.some((t) => t?.includes("Goal: ship X"))).toBe(false);

        // No duplicate type:"user" provider event for the compaction entry,
        // and exactly one compaction provider event whose key matches the row.
        const compactionEvents = extracted.providerEvents.filter(
            (e) => e.type === "compaction",
        );
        expect(compactionEvents.length).toBe(1);
        const userEventsForU2 = extracted.providerEvents.filter(
            (e) => e.providerEventId === "u2" && e.type === "user",
        );
        expect(userEventsForU2.length).toBe(0);
        const eventKey = agentEventRecordKey({
            provider: "claude",
            providerSessionId: "cl-1",
            providerEventId: "u2",
            seq: compactionEvents[0].seq,
        });
        expect(extracted.compactions[0].agentEventKey).toBe(eventKey);
    });
});

describe("claude token usage", () => {
    const usageLines = (model: string) => [
        JSON.stringify({
            type: "user",
            uuid: "u1",
            timestamp: "2026-06-01T10:00:00.000Z",
            sessionId: "cl-tok",
            cwd: "/tmp",
            message: { role: "user", content: "do a thing" },
        }),
        JSON.stringify({
            type: "assistant",
            uuid: "a1",
            timestamp: "2026-06-01T10:00:01.000Z",
            sessionId: "cl-tok",
            message: {
                role: "assistant",
                model,
                content: "ok",
                usage: {
                    input_tokens: 100,
                    output_tokens: 50,
                    cache_creation_input_tokens: 200,
                    cache_read_input_tokens: 1000,
                },
            },
        }),
        JSON.stringify({
            type: "assistant",
            uuid: "a2",
            timestamp: "2026-06-01T10:00:02.000Z",
            sessionId: "cl-tok",
            message: {
                role: "assistant",
                model,
                content: "done",
                usage: {
                    input_tokens: 10,
                    output_tokens: 5,
                    cache_creation_input_tokens: 0,
                    cache_read_input_tokens: 2000,
                },
            },
        }),
    ];

    test("sums per-message usage with cache-inclusive prompt totals", () => {
        const extracted = __testExtractClaudeJsonlLines(
            usageLines("claude-opus-4-8"),
            "-tmp",
            "cl-tok",
        );
        expect(extracted?.tokenUsage).not.toBeNull();
        const u = extracted!.tokenUsage!;
        // prompt = fresh(110) + cacheCreation(200) + cacheRead(3000) = 3310
        expect(u.promptTokens).toBe(3310);
        expect(u.completionTokens).toBe(55);
        expect(u.cacheCreationInputTokens).toBe(200);
        expect(u.cacheReadInputTokens).toBe(3000);
        expect(u.estimatedTokens).toBe(3365);
        expect(u.model).toBe("claude-opus-4-8");
    });

    test("prices the session via the built-in catalog", () => {
        const extracted = __testExtractClaudeJsonlLines(
            usageLines("claude-opus-4-8"),
            "-tmp",
            "cl-tok",
        );
        const [stmt] = buildClaudeTokenUsageStatements(extracted!);
        expect(stmt).toContain("UPSERT session_token_usage:");
        expect(stmt).toContain("pricing_source:");
        // fresh 110 @ $5/M + output 55 @ $25/M + cacheCreate 200 @ $6.25/M
        // + cacheRead 3000 @ $0.5/M = 0.00055 + 0.001375 + 0.00125 + 0.0015
        expect(stmt).toContain("estimated_cost_usd: 0.004675");
        expect(stmt).toContain('source: "claude"');
    });

    test("subagent source override lands on session and turn usage rows", () => {
        const extracted = __testExtractClaudeJsonlLines(
            usageLines("claude-opus-4-8"),
            "-tmp",
            "claude-subagent-abc",
        );
        const [stmt] = buildClaudeTokenUsageStatements(extracted!, "claude-subagent");
        expect(stmt).toContain('source: "claude-subagent"');
        const [turnStmt] = buildClaudeTurnTokenUsageStatements(extracted!, "claude-subagent");
        expect(turnStmt).toContain('source: "claude-subagent"');
    });

    test("emits no statements when the transcript carries no usage", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    uuid: "u1",
                    timestamp: "2026-06-01T10:00:00.000Z",
                    sessionId: "cl-none",
                    cwd: "/tmp",
                    message: { role: "user", content: "hi" },
                }),
            ],
            "-tmp",
            "cl-none",
        );
        expect(extracted?.tokenUsage).toBeNull();
        expect(buildClaudeTokenUsageStatements(extracted!)).toEqual([]);
    });

    test("leaves cost null for an unknown model but still records tokens", () => {
        const extracted = __testExtractClaudeJsonlLines(
            usageLines("some-unpriced-model"),
            "-tmp",
            "cl-tok",
        );
        const [stmt] = buildClaudeTokenUsageStatements(extracted!);
        expect(stmt).toContain("estimated_cost_usd: NONE");
        expect(stmt).toContain("pricing_source: NONE");
        expect(stmt).toContain("prompt_tokens: 3310");
    });

    test("emits a priced turn_token_usage row per assistant message", () => {
        const extracted = __testExtractClaudeJsonlLines(
            usageLines("claude-opus-4-8"),
            "-tmp",
            "cl-tok",
        );
        const stmts = buildClaudeTurnTokenUsageStatements(extracted!);
        // Two assistant messages -> two per-turn rows.
        expect(stmts).toHaveLength(2);
        expect(stmts[0]).toContain("UPSERT turn_token_usage:");
        expect(stmts[0]).toContain("usage_source: \"claude_transcript.message_usage\"");
        // First turn: fresh 100 @ $5/M + output 50 @ $25/M + cacheCreate 200
        // @ $6.25/M + cacheRead 1000 @ $0.5/M = 0.0005+0.00125+0.00125+0.0005
        expect(stmts[0]).toContain("estimated_cost_usd: 0.0035");
        expect(stmts[0]).toContain("prompt_tokens: 1300");
    });

    test("emits no turn rows when the transcript carries no usage", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    uuid: "u1",
                    timestamp: "2026-06-01T10:00:00.000Z",
                    sessionId: "cl-none",
                    cwd: "/tmp",
                    message: { role: "user", content: "hi" },
                }),
            ],
            "-tmp",
            "cl-none",
        );
        expect(buildClaudeTurnTokenUsageStatements(extracted!)).toEqual([]);
    });

    test("counts malformed lines at the decode boundary without dropping valid ones", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                "{ not json at all",
                JSON.stringify(["an", "array", "line"]),
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:00.000Z",
                    message: { role: "user", content: "Do the thing." },
                }),
                "\"just a string\"",
                JSON.stringify({
                    type: "assistant",
                    timestamp: "2026-05-09T09:00:01.000Z",
                    message: {
                        role: "assistant",
                        content: [{ type: "text", text: "Done." }],
                    },
                }),
            ],
            "-tmp-project",
            "cl-malformed",
        );
        expect(extracted).not.toBeNull();
        expect(extracted!.turns).toHaveLength(2);
        // unparseable JSON + two parseable-but-non-record lines
        expect(extracted!.malformedLines).toBe(3);
    });

    test("tolerates wrong-typed head fields on otherwise valid lines", () => {
        const extracted = __testExtractClaudeJsonlLines(
            [
                JSON.stringify({
                    type: "user",
                    timestamp: "2026-05-09T09:00:00.000Z",
                    cwd: { not: "a-string" },
                    isCompactSummary: "not-a-boolean",
                    message: { role: "user", content: "hello" },
                }),
            ],
            "-tmp-project",
            "cl-tolerant",
        );
        expect(extracted).not.toBeNull();
        expect(extracted!.malformedLines).toBe(0);
        expect(extracted!.turns).toHaveLength(1);
        expect(extracted!.turns[0].text).toBe("hello");
        expect(extracted!.session.cwd).toBeNull();
    });
});
